	private ["_unit","_eat","_drink","_fixSlot"];
	_unit = _this select 0;  
	_eat = _this select 1;  
	_fixSlot = binocular player;  
	_hunger=_unit getVariable ["ARMST_THIRST",1];
	_goggles = goggles _unit;
	disableUserInput true;
	_unit removeitem "armst_item_vodka";  
	_unit addweapon "armst_switch_vodka"; 
	[_unit] call AGM_WeaponSelect_fnc_putWeaponAway;  
	sleep 1; 
	_unit selectWeapon "armst_switch_vodka"; 
	_unit switchmove "AmovPercMstpSoptWbinDnon";  
	_unit playactionnow "GestureDrink";
	player say2d "drinking"; 
	armst_radiation_infection = 0;
	sleep 7;
	["Слегка нажрался..."] call AGM_Core_fnc_displayTextStructured;
	addcamshake [6,240,2];
	_unit removeweapon "armst_switch_vodka";  
	_unit additem "armst_item_vodkaempty";  
	disableUserInput false;
	player addWeapon _fixSlot;