class CfgPatches
{
	class armst_zahvat2_anim
	{
		units[]={};
		weapons[]={};
		requiredVersion=1.02;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR",
			"A3_Characters_F",
			"A3_Sounds_F",
			"A3_Data_F",
			"A3_Sounds_F",
			"A3_Anims_F"
		};
	};
};
class DefaultEventhandlers;
class CfgMovesAnimalsBase
{
	class Default
	{
		actions="";
		access=3;
		file="";
		looped=1;
		speed=0.5;
		disableWeapons=1;
		enableOptics=0;
		disableWeaponsLong=1;
		showWeaponAim=0;
		enableMissile=0;
		enableBinocular=0;
		showItemInHand=0;
		showItemInRightHand=0;
		showHandGun=0;
		onLandBeg=0;
		onLandEnd=0;
		onLadder=0;
		canPullTrigger=1;
		duty=-0.50999999;
		predictSpeedCoef=1;
		visibleSize=1;
		aimPrecision=1;
		relSpeedMin=1;
		relSpeedMax=1;
		soundEnabled=0;
		controlHead=0;
		headBobMode=0;
		headBobStrength=0;
		soundOverride="";
		soundEdge[]={0.5,1};
		terminal=0;
		limitGunMovement=1;
		variantsPlayer[]={};
		variantsAI[]=
		{
			""
		};
		equivalentTo="";
		connectAs="";
		variantAfter[]={5,10,20};
		connectFrom[]={};
		connectTo[]={};
		interpolateWith[]={};
		interpolateTo[]={};
		interpolateFrom[]={};
		aiming="aimingNo";
		leaning="aimingNo";
		untiltWeapon="aimingNo";
		aimingBody="aimingUpDefault";
		legs="legsNo";
		head="headDefault";
		leaningFactorBeg=0;
		leaningFactorEnd=0;
		leaningFactorZeroPoint=-1;
		leaningCorrectionAngleBeg=0;
		leaningCorrectionAngleEnd=0;
		interpolationSpeed=6;
		interpolationRestart=0;
		collisionShape="ca\animals2\data\geom\basicColide.p3d";
		hasCollShapeSafe=0;
		collisionShapeSafe="";
		boundingSphere=1;
		enableDirectControl=1;
		enableAutoActions=0;
		leftHandIKBeg=0;
		leftHandIKEnd=0;
		rightHandIKBeg=0;
		rightHandIKEnd=0;
		weaponIK=0;
		preload=0;
		walkcycles=1;
		forceAim=0;
		rightHandIKCurve[]={};
		leftHandIKCurve[]={};
	};
	class StandBase: Default
	{
		aiming="aimingDefault";
		disableWeapons=1;
		canReload=1;
		weaponLowered=0;
		weaponObstructed=0;
		canBlendStep=1;
		useIdles=1;
		adjstance="m";
		leaningFactorBeg=1;
		leaningFactorEnd=1;
	};
	class DefaultDie: Default
	{
		aiming="aimingNo";
		legs="legsNo";
		head="headNo";
		disableWeapons=1;
		canReload=1;
		weaponLowered=0;
		weaponObstructed=0;
		canBlendStep=1;
		useIdles=1;
		adjstance="m";
		interpolationRestart=1;
		soundOverride="fallbody";
		soundEdge[]={0.44999999};
		soundEnabled=1;
	};
	class ManActions
	{
		AdjustF="zahvat2_StopV2";
		AdjustB="zahvat2_StopV2";
		AdjustL="zahvat2_StopV2";
		AdjustR="zahvat2_StopV2";
		AdjustLF="zahvat2_StopV2";
		AdjustLB="zahvat2_StopV2";
		AdjustRB="zahvat2_StopV2";
		AdjustRF="zahvat2_StopV2";
		dooraction="zahvat2_StopV2";
		GestureLegPush="zahvat2_StopV2";
		agonyStart="zahvat2_StopV2";
		agonyStop="zahvat2_StopV2";
		medicStop="zahvat2_StopV2";
		medicStart="zahvat2_StopV2";
		medicStartUp="zahvat2_StopV2";
		medicStartRightSide="zahvat2_StopV2";
		GestureAgonyCargo="zahvat2_StopV2";
		grabCarry="zahvat2_StopV2";
		grabCarried="zahvat2_StopV2";
		grabDrag="zahvat2_StopV2";
		grabDragged="zahvat2_StopV2";
		carriedStill="zahvat2_StopV2";
		released="zahvat2_StopV2";
		releasedBad="zahvat2_StopV2";
		Stop="zahvat2_StopV2";
		StopRelaxed="zahvat2_StopV2";
		TurnL="zahvat2_StopV2";
		TurnR="zahvat2_StopV2";
		TurnLRelaxed="zahvat2_StopV2";
		TurnRRelaxed="zahvat2_StopV2";
		ReloadMagazine="zahvat2_StopV2";
		reloadGM6="zahvat2_StopV2";
		ReloadMGun="zahvat2_StopV2";
		ReloadRPG="zahvat2_StopV2";
		ReloadMortar="zahvat2_StopV2";
		ThrowPrepare="zahvat2_StopV2";
		ThrowGrenade="zahvat2_StopV2";
		WalkF="zahvat2_StopV2";
		WalkLF="zahvat2_StopV2";
		WalkRF="zahvat2_StopV2";
		WalkL="zahvat2_StopV2";
		WalkR="zahvat2_StopV2";
		WalkLB="zahvat2_StopV2";
		WalkRB="zahvat2_StopV2";
		WalkB="zahvat2_StopV2";
		PlayerWalkF="zahvat2_StopV2";
		PlayerWalkLF="zahvat2_StopV2";
		PlayerWalkRF="zahvat2_StopV2";
		PlayerWalkL="zahvat2_StopV2";
		PlayerWalkR="zahvat2_StopV2";
		PlayerWalkLB="zahvat2_StopV2";
		PlayerWalkRB="zahvat2_StopV2";
		PlayerWalkB="zahvat2_StopV2";
		SlowF="zahvat2_StopV2";
		SlowLF="zahvat2_StopV2";
		SlowRF="zahvat2_StopV2";
		SlowL="zahvat2_StopV2";
		SlowR="zahvat2_StopV2";
		SlowLB="zahvat2_StopV2";
		SlowRB="zahvat2_StopV2";
		SlowB="zahvat2_StopV2";
		PlayerSlowF="zahvat2_StopV2";
		PlayerSlowLF="zahvat2_StopV2";
		PlayerSlowRF="zahvat2_StopV2";
		PlayerSlowL="zahvat2_StopV2";
		PlayerSlowR="zahvat2_StopV2";
		PlayerSlowLB="zahvat2_StopV2";
		PlayerSlowRB="zahvat2_StopV2";
		PlayerSlowB="zahvat2_StopV2";
		FastF="zahvat2_StopV2";
		FastLF="zahvat2_StopV2";
		FastRF="zahvat2_StopV2";
		FastL="zahvat2_StopV2";
		FastR="zahvat2_StopV2";
		FastLB="zahvat2_StopV2";
		FastRB="zahvat2_StopV2";
		FastB="zahvat2_StopV2";
		TactF="zahvat2_StopV2";
		TactLF="zahvat2_StopV2";
		TactRF="zahvat2_StopV2";
		TactL="zahvat2_StopV2";
		TactR="zahvat2_StopV2";
		TactLB="zahvat2_StopV2";
		TactRB="zahvat2_StopV2";
		TactB="zahvat2_StopV2";
		PlayerTactF="zahvat2_StopV2";
		PlayerTactLF="zahvat2_StopV2";
		PlayerTactRF="zahvat2_StopV2";
		PlayerTactL="zahvat2_StopV2";
		PlayerTactR="zahvat2_StopV2";
		PlayerTactLB="zahvat2_StopV2";
		PlayerTactRB="zahvat2_StopV2";
		PlayerTactB="zahvat2_StopV2";
		EvasiveLeft="zahvat2_StopV2";
		EvasiveRight="zahvat2_StopV2";
		startSwim="zahvat2_StopV2";
		surfaceSwim="zahvat2_StopV2";
		bottomSwim="zahvat2_StopV2";
		StopSwim="zahvat2_StopV2";
		startDive="zahvat2_StopV2";
		SurfaceDive="zahvat2_StopV2";
		BottomDive="zahvat2_StopV2";
		StopDive="zahvat2_StopV2";
		Down="zahvat2_StopV2";
		Up="zahvat2_StopV2";
		PlayerStand="zahvat2_StopV2";
		PlayerCrouch="zahvat2_StopV2";
		PlayerProne="zahvat2_StopV2";
		Lying="zahvat2_StopV2";
		Stand="zahvat2_StopV2";
		Combat="zahvat2_StopV2";
		Crouch="zahvat2_StopV2";
		CanNotMove="zahvat2_StopV2";
		Civil="zahvat2_StopV2";
		CivilLying="zahvat2_StopV2";
		FireNotPossible="zahvat2_StopV2";
		Die="zahvat2_StopV2";
		Unconscious="zahvat2_StopV2";
		WeaponOn="zahvat2_StopV2";
		WeaponOff="zahvat2_StopV2";
		Default="zahvat2_StopV2";
		JumpOff="zahvat2_StopV2";
		StrokeFist="zahvat2_StopV2";
		StrokeGun="zahvat2_StopV2";
		SitDown="zahvat2_StopV2";
		Salute="zahvat2_StopV2";
		saluteOff="zahvat2_StopV2";
		GetOver="zahvat2_StopV2";
		Diary="zahvat2_StopV2";
		Surrender="zahvat2_StopV2";
		Gear="zahvat2_StopV2";
		BinocOn="zahvat2_StopV2";
		BinocOff="zahvat2_StopV2";
		PutDown="zahvat2_StopV2";
		PutDownEnd="zahvat2_StopV2";
		Medic="zahvat2_StopV2";
		MedicOther="zahvat2_StopV2";
		Treated="zahvat2_StopV2";
		LadderOnDown="zahvat2_StopV2";
		LadderOnUp="zahvat2_StopV2";
		LadderOff="zahvat2_StopV2";
		LadderOffTop="zahvat2_StopV2";
		LadderOffBottom="zahvat2_StopV2";
		GetInLow="zahvat2_StopV2";
		GetInMedium="zahvat2_StopV2";
		GetInHigh="zahvat2_StopV2";
		GetInVertical="zahvat2_StopV2";
		GetInSDV="zahvat2_StopV2";
		GetInHeli_Attack_01Pilot="zahvat2_StopV2";
		GetInHeli_Attack_01Gunner="zahvat2_StopV2";
		GetInHelicopterCargo="zahvat2_StopV2";
		GetInMRAP_01="zahvat2_StopV2";
		GetInMRAP_01_cargo="zahvat2_StopV2";
		GetOutMRAP_01="zahvat2_StopV2";
		GetOutMRAP_01_cargo="zahvat2_StopV2";
		GetOutHelicopterCargo="zahvat2_StopV2";
		GetOutLow="zahvat2_StopV2";
		GetOutMedium="zahvat2_StopV2";
		GetOutHigh="zahvat2_StopV2";
		GetOutHighZamak="zahvat2_StopV2";
		GetOutHighHemtt="zahvat2_StopV2";
		GetOutSDV="zahvat2_StopV2";
		GetOutHeli_Attack_01Pilot="zahvat2_StopV2";
		GetOutHeli_Attack_01Gunner="zahvat2_StopV2";
		GetInBoat="zahvat2_StopV2";
		GetOutBoat="zahvat2_StopV2";
		TakeFlag="zahvat2_StopV2";
		HandGunOn="zahvat2_StopV2";
		gestureAttack="zahvat2_StopV2";
		gestureGo="zahvat2_StopV2";
		gestureGoB="zahvat2_StopV2";
		gestureFreeze="zahvat2_StopV2";
		gesturePoint="zahvat2_StopV2";
		gestureCeaseFire="zahvat2_StopV2";
		gestureCover="zahvat2_StopV2";
		gestureUp="zahvat2_StopV2";
		gestureNo="zahvat2_StopV2";
		gestureYes="zahvat2_StopV2";
		gestureFollow="zahvat2_StopV2";
		gestureAdvance="zahvat2_StopV2";
		gestureHi="zahvat2_StopV2";
		gestureHiB="zahvat2_StopV2";
		gestureHiC="zahvat2_StopV2";
		gestureNod="zahvat2_StopV2";
		GestureSpasm0="zahvat2_StopV2";
		GestureSpasm1="zahvat2_StopV2";
		GestureSpasm2="zahvat2_StopV2";
		GestureSpasm3="zahvat2_StopV2";
		GestureSpasm4="zahvat2_StopV2";
		GestureSpasm5="zahvat2_StopV2";
		GestureSpasm6="zahvat2_StopV2";
		GestureSpasm0weak="zahvat2_StopV2";
		GestureSpasm1weak="zahvat2_StopV2";
		GestureSpasm2weak="zahvat2_StopV2";
		GestureSpasm3weak="zahvat2_StopV2";
		GestureSpasm4weak="zahvat2_StopV2";
		GestureSpasm5weak="zahvat2_StopV2";
		GestureSpasm6weak="zahvat2_StopV2";
		GestureReloadMX="zahvat2_StopV2";
		GestureReloadMXCompact="zahvat2_StopV2";
		GestureReloadMXSniper="zahvat2_StopV2";
		GestureReloadMk20="zahvat2_StopV2";
		GestureReloadMk20UGL="zahvat2_StopV2";
		GestureReloadMXUGL="zahvat2_StopV2";
		GestureReloadTRG="zahvat2_StopV2";
		GestureReloadTRGUGL="zahvat2_StopV2";
		GestureReloadKatiba="zahvat2_StopV2";
		GestureReloadKatibaUGL="zahvat2_StopV2";
		GestureReloadM200="zahvat2_StopV2";
		GestureReloadLRR="zahvat2_StopV2";
		GestureReloadEBR="zahvat2_StopV2";
		GestureReloadM4SSAS="zahvat2_StopV2";
		GestureReloadSMG_02="zahvat2_StopV2";
		GestureReloadSMG_03="zahvat2_StopV2";
		GestureReloadPistol="zahvat2_StopV2";
		GestureReloadPistolHeavy02="zahvat2_StopV2";
		GestureReloadFlaregun="zahvat2_StopV2";
		GestureReloadSMG_01="zahvat2_StopV2";
		GestureReloadSDAR="zahvat2_StopV2";
		GestureReloadDMR="zahvat2_StopV2";
		GestureReloadDMR02="zahvat2_StopV2";
		GestureReloadDMR03="zahvat2_StopV2";
		GestureReloadDMR04="zahvat2_StopV2";
		GestureReloadDMR05="zahvat2_StopV2";
		GestureReloadDMR06="zahvat2_StopV2";
		GestureReloadMMG01="zahvat2_StopV2";
		GestureReloadMMG02="zahvat2_StopV2";
		MountOptic="zahvat2_StopV2";
		DismountOptic="zahvat2_StopV2";
		MountSide="zahvat2_StopV2";
		DismountSide="zahvat2_StopV2";
		GestureMountMuzzle="zahvat2_StopV2";
		GestureDismountMuzzle="zahvat2_StopV2";
		healedStart="zahvat2_StopV2";
		healedStop="zahvat2_StopV2";
		TestDriver="zahvat2_StopV2";
		TestDriverOut="zahvat2_StopV2";
		TestGunner="zahvat2_StopV2";
		Relax="zahvat2_StopV2";
		swimUp="zahvat2_StopV2";
		swimDown="zahvat2_StopV2";
		StartFreefall="zahvat2_StopV2";
		PrimaryWeapon="zahvat2_StopV2";
		SecondaryWeapon="zahvat2_StopV2";
		Binoculars="zahvat2_StopV2";
		FDStart="zahvat2_StopV2";
		Obstructed="zahvat2_StopV2";
	};
	class BlendAnims
	{
		aimingDefault[]={};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]={};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};
	collisionVertexPattern[]=
	{
		"1a",
		"2a",
		"3a",
		"4a",
		"5a",
		"6a",
		"7a",
		"8a",
		"9a",
		"10a",
		"11a",
		"12a",
		"13a",
		"14a",
		"15a",
		"16a",
		"17a",
		"18a",
		"19a",
		"20a",
		"21a",
		"22a",
		"23a",
		"24a",
		"25a",
		"26a",
		"27a",
		"28a",
		"29a",
		"30a",
		"31a",
		"32a",
		"33a",
		"34a"
	};
	collisionGeomCompPattern[]={1};
};
class CfgMoveszahvat2: CfgMovesAnimalsBase
{
	primaryActionMaps[]=
	{
		"zahvat2Actions",
		"NoActions"
	};
	skeletonName="Zahvat2Skeleton";
	gestures="CfgGesturesMale";
	extended="CfgExtendedAnimation";
	class States
	{
		class zahvat2_Stop: StandBase
		{
			actions="zahvat2Actions";
			duty=-1;
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			variantsAI[]={};
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			variantAfter[]={0,2,3};
			speed=0.25;
			relSpeedMin=0.69999999;
			relSpeedMax=1.1;
			looped=1;
			collisionShape="A3\anims_f\Data\Geom\Sdr\Perc_Wnon.p3d";
			ConnectTo[]=
			{
				"zahvat2_TurnR",
				0.1,
				"zahvat2_TurnL",
				0.1,
				"zahvat2_Sprint",
				0.02,
				"zahvat2_Run",
				0.02,
				"zahvat2_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat2_TurnR",
				0.1,
				"zahvat2_Die",
				0.02,
				"zahvat2_TurnL",
				0.1,
				"zahvat2_Sprint",
				0.02,
				"zahvat2_Run",
				0.02,
				"zahvat2_Walk",
				0.2
			};
		};
		class zahvat2_angry: zahvat2_Stop
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
			looped=1;
			ConnectTo[]=
			{
				"zahvat2_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat2_Stop",
				0.02
			};
		};
		class zahvat2_attack1: zahvat2_Stop
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat2_attack2: zahvat2_Stop
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat2_attack3: zahvat2_Stop
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat2_attack4: zahvat2_Stop
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat2_TurnL: zahvat2_Stop
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
			ConnectTo[]=
			{
				"zahvat2_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat2_Stop",
				0.1
			};
		};
		class zahvat2_TurnR: zahvat2_TurnL
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
			ConnectTo[]=
			{
				"zahvat2_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat2_Stop",
				0.1
			};
		};
		class zahvat2_StopV1: zahvat2_Stop
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
			looped=1;
			ConnectTo[]=
			{
				"zahvat2_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat2_Stop",
				0.02
			};
		};
		class zahvat2_Sprint: zahvat2_Stop
		{
			actions="zahvat2Sprint";
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
			duty=0.5;
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			ConnectTo[]=
			{
				"zahvat2_Stop",
				0.02,
				"zahvat2_Run",
				0.02,
				"zahvat2_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat2_Die",
				0.02,
				"zahvat2_Stop",
				0.02,
				"zahvat2_Run",
				0.02,
				"zahvat2_Walk",
				0.2
			};
		};
		class zahvat2_Run: zahvat2_Stop
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
			duty=-0.5;
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			ConnectTo[]=
			{
				"zahvat2_Stop",
				0.02,
				"zahvat2_Sprint",
				0.02,
				"zahvat2_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat2_Die",
				0.02,
				"zahvat2_Stop",
				0.02,
				"zahvat2_Sprint",
				0.02,
				"zahvat2_Walk",
				0.2
			};
		};
		class zahvat2_Walk: zahvat2_Stop
		{
			duty=-0.69999999;
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			ConnectTo[]=
			{
				"zahvat2_Stop",
				0.2,
				"zahvat2_Sprint",
				0.2,
				"zahvat2_Run",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat2_Die",
				0.02,
				"zahvat2_Stop",
				0.2,
				"zahvat2_Sprint",
				0.2,
				"zahvat2_Run",
				0.2
			};
		};
		class zahvat2_Die: DefaultDie
		{
			file="\armst\armst_char\char_mut\zahvat2\anim\idle.rtm";
			speed=0.25;
			looped=0;
			onLandBeg=1;
			onLandEnd=1;
			soundEnabled=0;
			terminal=1;
			ragdoll=1;
			headBobMode=4;
			headBobStrength=-1;
			disableWeapons=1;
			disableWeaponsLong=1;
		};
	};
	class Actions
	{
		class NoActions: ManActions
		{
			turnSpeed=8;
			limitFast=5.5;
			useFastMove=0;
			upDegree=0;
			stance="zahvat2_Stop";
		};
		class zahvat2Actions: NoActions
		{
			Stop="zahvat2_Stop";
			StopRelaxed="zahvat2_Stop";
			TurnL="zahvat2_Stop";
			TurnR="zahvat2_Stop";
			TurnLRelaxed="zahvat2_Stop";
			TurnRRelaxed="zahvat2_Stop";
			Default="zahvat2_Stop";
			JumpOff="zahvat2_Stop";
			WalkF="zahvat2_Stop";
			SlowF="zahvat2_Stop";
			FastF="zahvat2_Stop";
			EvasiveForward="zahvat2_Stop";
			Down="zahvat2_Stop";
			Up="zahvat2_Stop";
			PlayerStand="zahvat2_Stop";
			PlayerProne="zahvat2_Stop";
			PlayerCrouch="zahvat2_Stop";
			Crouch="zahvat2_Stop";
			Lying="zahvat2_Stop";
			Stand="zahvat2_Stop";
			Combat="zahvat2_Stop";
			CanNotMove="zahvat2_Stop";
			Civil="zahvat2_Stop";
			CivilLying="zahvat2_Stop";
			FireNotPossible="zahvat2_Stop";
			Die="zahvat2_Die";
			turnSpeed=1;
			limitFast=1.5;
			useFastMove=0;
			upDegree="ManPosNoWeapon";
			StartSwim="zahvat2_Die";
		};
		class zahvat2Sprint: zahvat2Actions
		{
			Die="zahvat2_Die";
			TurnL="zahvat2_Stop";
			TurnR="zahvat2_Stop";
			TurnLRelaxed="zahvat2_Stop";
			TurnRRelaxed="zahvat2_Stop";
			turnSpeed=10;
			limitFast=1.5;
			useFastMove=1;
		};
	};
	class Interpolations
	{
	};
	transitionsInterpolated[]={};
	transitionsSimple[]={};
	transitionsDisabled[]={};
	class BlendAnims: BlendAnims
	{
		aimingDefault[]={};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]={};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};
};
