class CfgPatches
{
	class Monsters
	{
		units[]={};
		weapons[]={};
		requiredVersion=1.02;
		requiredAddons[]={};
	};
};
class CfgSkeletonParameters
{
	class OFP2_ManSkeleton
	{
		pivotsModel="\armst\armst_anim\OFP2_ManSkeleton_Pivots.p3d";
	};
};
class DefaultEventhandlers;
class CfgMovesAnimalsBase
{
	class Default
	{
		actions="";
		access=3;
		file="";
		looped=1;
		speed=0.5;
		disableWeapons=1;
		enableOptics=0;
		disableWeaponsLong=1;
		showWeaponAim=0;
		enableMissile=0;
		enableBinocular=0;
		showItemInHand=0;
		showItemInRightHand=0;
		showHandGun=0;
		onLandBeg=0;
		onLandEnd=0;
		onLadder=0;
		canPullTrigger=1;
		duty=-0.50999999;
		predictSpeedCoef=1;
		visibleSize=1;
		aimPrecision=1;
		relSpeedMin=1;
		relSpeedMax=1;
		soundEnabled=0;
		controlHead=0;
		headBobMode=0;
		headBobStrength=0;
		soundOverride="";
		soundEdge[]={0.5,1};
		terminal=0;
		limitGunMovement=1;
		variantsPlayer[]={};
		variantsAI[]=
		{
			""
		};
		equivalentTo="";
		connectAs="";
		variantAfter[]={5,10,20};
		connectFrom[]={};
		connectTo[]={};
		interpolateWith[]={};
		interpolateTo[]={};
		interpolateFrom[]={};
		aiming="aimingNo";
		leaning="aimingNo";
		untiltWeapon="aimingNo";
		aimingBody="aimingUpDefault";
		legs="legsNo";
		head="headDefault";
		leaningFactorBeg=0;
		leaningFactorEnd=0;
		leaningFactorZeroPoint=-1;
		leaningCorrectionAngleBeg=0;
		leaningCorrectionAngleEnd=0;
		interpolationSpeed=6;
		interpolationRestart=0;
		collisionShape="";
		hasCollShapeSafe=0;
		collisionShapeSafe="";
		boundingSphere=1;
		enableDirectControl=1;
		enableAutoActions=0;
		leftHandIKBeg=0;
		leftHandIKEnd=0;
		rightHandIKBeg=0;
		rightHandIKEnd=0;
		weaponIK=0;
		preload=0;
		walkcycles=1;
		forceAim=0;
		rightHandIKCurve[]={};
		leftHandIKCurve[]={};
	};
	class StandBase: Default
	{
		aiming="aimingDefault";
		disableWeapons=1;
		leaningFactorBeg=1;
		leaningFactorEnd=1;
	};
	class DefaultDie: Default
	{
		aiming="aimingNo";
		legs="legsNo";
		head="headNo";
		disableWeapons=1;
		interpolationRestart=1;
		soundOverride="fallbody";
		soundEdge[]={0.44999999};
		soundEnabled=0;
	};
	class ManActions
	{
		Stop="";
		StopRelaxed="";
		TurnL="";
		TurnR="";
		TurnLRelaxed="";
		TurnRRelaxed="";
		Default="";
		JumpOff="";
		ReloadMagazine="";
		ReloadMGun="";
		ReloadAT="";
		ReloadMortar="";
		ThrowGrenade="";
		WalkF="";
		WalkLF="";
		WalkRF="";
		WalkL="";
		WalkR="";
		WalkLB="";
		WalkRB="";
		WalkB="";
		SlowF="";
		SlowLF="";
		SlowRF="";
		SlowL="";
		SlowR="";
		SlowLB="";
		SlowRB="";
		SlowB="";
		FastF="";
		FastLF="";
		FastRF="";
		FastL="";
		FastR="";
		FastLB="";
		FastRB="";
		FastB="";
		EvasiveForward="";
		EvasiveLeft="";
		EvasiveRight="";
		EvasiveBack="";
		StartSwim="";
		StopSwim="";
		Down="";
		Up="";
		PlayerStand="";
		PlayerCrouch="";
		PlayerProne="";
		Lying="";
		Stand="";
		Combat="";
		Crouch="";
		CanNotMove="";
		Civil="";
		CivilLying="";
		FireNotPossible="";
		Die="";
		WeaponOn="";
		WeaponOff="";
		StrokeFist="";
		StrokeGun="";
		SitDown="";
		Salute="";
		BinocOn="";
		BinocOff="";
		PutDown="";
		PutDownEnd="";
		Medic="";
		Treated="";
		LadderOnDown="";
		LadderOnUp="";
		LadderOff="";
		LadderOffTop="";
		LadderOffBottom="";
		GetInLow="";
		GetInMedium="";
		GetInHigh="";
		GetOutLow="";
		GetOutMedium="";
		GetOutHigh="";
		TakeFlag="";
		HandGunOn="";
		LookAround="";
		Eat="";
		StopEat="";
		Rest="";
		StopRest="";
	};
	class BlendAnims
	{
		aimingDefault[]={};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]={};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};
	collisionVertexPattern[]=
	{
		"1a",
		"2a",
		"3a",
		"4a",
		"5a",
		"6a",
		"7a",
		"8a",
		"9a",
		"10a",
		"11a",
		"12a",
		"13a",
		"14a",
		"15a",
		"16a",
		"17a",
		"18a",
		"19a",
		"20a",
		"21a",
		"22a",
		"23a",
		"24a",
		"25a",
		"26a",
		"27a",
		"28a",
		"29a",
		"30a",
		"31a",
		"32a",
		"33a",
		"34a"
	};
	collisionGeomCompPattern[]={1};
};
class CfgMovesKrovosos: CfgMovesAnimalsBase
{
	primaryActionMaps[]=
	{
		"bloodsuckerActions",
		"NoActions"
	};
	skeletonName="OFP2_ManSkeleton";
	gestures="CfgGesturesMale";
	extended="CfgExtendedAnimation";
	class States
	{
		class bloodsucker_Stop: StandBase
		{
			actions="bloodsuckerActions";
			duty=-1;
			file="\armst\armst_anim\krovosos\idle02.rtm";
			variantsAI[]={};
			variantAfter[]={0,2,3};
			speed=1;
			relSpeedMin=0.69999999;
			relSpeedMax=1.1;
			looped=1;
			collisionShape="A3\anims_f\Data\Geom\Sdr\Perc_Wnon.p3d";
			ConnectTo[]=
			{
				"bloodsucker_TurnR",
				0.1,
				"bloodsucker_TurnL",
				0.1,
				"bloodsucker_Sprint",
				0.02,
				"bloodsucker_Run",
				0.02,
				"bloodsucker_Walk",
				0.2,
				"bloodsucker_Sit1",
				0.1
			};
			InterpolateTo[]=
			{
				"bloodsucker_TurnR",
				0.1,
				"bloodsucker_Die",
				0.02,
				"bloodsucker_TurnL",
				0.1,
				"bloodsucker_Sprint",
				0.02,
				"bloodsucker_Run",
				0.02,
				"bloodsucker_Walk",
				0.2
			};
		};
		class bloodsucker_angry: bloodsucker_Stop
		{
			file="\armst\armst_anim\krovosos\angry.rtm";
			speed=1;
			looped=1;
			ConnectTo[]=
			{
				"bloodsucker_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"bloodsucker_Stop",
				0.02
			};
		};
		class bloodsucker_attack1: bloodsucker_angry
		{
			file="\armst\armst_anim\krovosos\attack01.rtm";
			speed=0.55000001;
		};
		class bloodsucker_attack2: bloodsucker_angry
		{
			file="\armst\armst_anim\krovosos\krovosos_attack01.rtm";
			speed=0.94999999;
		};
		class bloodsucker_attack3: bloodsucker_angry
		{
			file="\armst\armst_anim\krovosos\krovosos_attack02.rtm";
			speed=0.75;
		};
		class bloodsucker_attack4: bloodsucker_angry
		{
			file="\armst\armst_anim\krovosos\attack02.rtm";
			speed=0.55000001;
		};
		class bloodsucker_rus_attack3: bloodsucker_angry
		{
			file="\armst\armst_anim\krovosos\run_attack.rtm";
			speed=0.75;
		};
		class bloodsucker_TurnL: bloodsucker_Stop
		{
			file="\armst\armst_anim\krovosos\walk_fwd.rtm";
			speed=1.8;
			ConnectTo[]=
			{
				"bloodsucker_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"bloodsucker_Stop",
				0.1
			};
		};
		class bloodsucker_TurnR: bloodsucker_TurnL
		{
			file="\armst\armst_anim\krovosos\walk_fwd.rtm";
			speed=1.8;
			ConnectTo[]=
			{
				"bloodsucker_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"bloodsucker_Stop",
				0.1
			};
		};
		class bloodsucker_StopV1: bloodsucker_Stop
		{
			file="\armst\armst_anim\krovosos\idle03.rtm";
			speed=0.25;
			looped=1;
			ConnectTo[]=
			{
				"bloodsucker_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"bloodsucker_Die",
				0.02
			};
		};
		class bloodsucker_StopV2: bloodsucker_Stop
		{
			file="\armst\armst_anim\krovosos\idle01.rtm";
			speed=0.2;
			looped=1;
			ConnectTo[]=
			{
				"bloodsucker_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"bloodsucker_Die",
				0.02
			};
		};
		class bloodsucker_Sprint: bloodsucker_Stop
		{
			actions="bloodsuckerSprint";
			file="\armst\armst_anim\krovosos\run_fwd.rtm";
			speed=1.92;
			duty=0.5;
			ConnectTo[]=
			{
				"bloodsucker_Stop",
				0.02,
				"bloodsucker_Run",
				0.02,
				"bloodsucker_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"bloodsucker_Die",
				0.02,
				"bloodsucker_Stop",
				0.02,
				"bloodsucker_Run",
				0.02,
				"bloodsucker_Walk",
				0.2
			};
		};
		class bloodsucker_rus_attack1: bloodsucker_Sprint
		{
			file="\armst\armst_anim\krovosos\krovosos_run_attack03.rtm";
			speed=0.64999998;
		};
		class bloodsucker_rus_attack2: bloodsucker_Sprint
		{
			file="\armst\armst_anim\krovosos\krovosos_run_attack.rtm";
			speed=0.64999998;
		};
		class bloodsucker_Run: bloodsucker_Stop
		{
			file="\armst\armst_anim\krovosos\run_fwd.rtm";
			speed=1.663;
			duty=-0.5;
			ConnectTo[]=
			{
				"bloodsucker_Stop",
				0.02,
				"bloodsucker_Sprint",
				0.02,
				"bloodsucker_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"bloodsucker_Die",
				0.02,
				"bloodsucker_Stop",
				0.02,
				"bloodsucker_Sprint",
				0.02,
				"bloodsucker_Walk",
				0.2
			};
		};
		class bloodsucker_Walk: bloodsucker_Stop
		{
			duty=-0.69999999;
			file="\armst\armst_anim\krovosos\walk_steal.rtm";
			speed=0.55000001;
			ConnectTo[]=
			{
				"bloodsucker_Stop",
				0.2,
				"bloodsucker_Sprint",
				0.2,
				"bloodsucker_Run",
				0.2
			};
			InterpolateTo[]=
			{
				"bloodsucker_Die",
				0.02,
				"bloodsucker_Stop",
				0.2,
				"bloodsucker_Sprint",
				0.2,
				"bloodsucker_Run",
				0.2
			};
		};
		class bloodsucker_Die: DefaultDie
		{
			file="\A3\anims_f\Data\Anim\Sdr\dth\pne\stp\ras\Rfl\AdthPpneMstpSrasWrflDnon_1";
			speed=1.67;
			looped=0;
			onLandBeg=1;
			onLandEnd=1;
			soundEnabled=0;
			terminal=1;
			ragdoll=1;
			headBobMode=4;
			headBobStrength=-1;
			disableWeapons=1;
			disableWeaponsLong=1;
		};
	};
	class Actions
	{
		class NoActions: ManActions
		{
			turnSpeed=8;
			limitFast=5.5;
			useFastMove=0;
			upDegree=0;
		};
		class bloodsuckerActions: NoActions
		{
			Stop="bloodsucker_Stop";
			StopRelaxed="bloodsucker_StopV2";
			TurnL="bloodsucker_TurnL";
			TurnR="bloodsucker_TurnR";
			TurnLRelaxed="bloodsucker_TurnL";
			TurnRRelaxed="bloodsucker_TurnR";
			Default="bloodsucker_StopV1";
			JumpOff="bloodsucker_Run";
			WalkF="bloodsucker_Walk";
			SlowF="bloodsucker_Run";
			FastF="bloodsucker_Sprint";
			EvasiveForward="bloodsucker_Sprint";
			Down="bloodsucker_StopV1";
			Up="bloodsucker_Run";
			PlayerStand="bloodsucker_Run";
			PlayerProne="bloodsucker_Run";
			PlayerCrouch="bloodsucker_StopV1";
			Crouch="bloodsucker_StopV1";
			Lying="bloodsucker_StopV2";
			Stand="bloodsucker_Run";
			Combat="bloodsucker_Sprint";
			CanNotMove="bloodsucker_StopV2";
			Civil="bloodsucker_Run";
			CivilLying="bloodsucker_StopV2";
			FireNotPossible="bloodsucker_Run";
			Die="bloodsucker_Die";
			turnSpeed=1;
			limitFast=1.5;
			useFastMove=0;
			upDegree="ManPosNoWeapon";
			StartSwim="bloodsucker_Die";
		};
		class bloodsuckerSprint: bloodsuckerActions
		{
			Die="bloodsucker_Die";
			TurnL="bloodsucker_TurnL";
			TurnR="bloodsucker_TurnR";
			TurnLRelaxed="bloodsucker_TurnL";
			TurnRRelaxed="bloodsucker_TurnR";
			turnSpeed=10;
			limitFast=1.5;
			useFastMove=1;
		};
	};
	class Interpolations
	{
	};
	transitionsInterpolated[]={};
	transitionsSimple[]={};
	transitionsDisabled[]={};
	class BlendAnims: BlendAnims
	{
		aimingDefault[]=
		{
			"head",
			1,
			"Jaw",
			1,
			"Neck1",
			0.5,
			"Tongue1",
			1,
			"Tongue2",
			1
		};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]=
		{
			"head",
			1,
			"Jaw",
			1,
			"Neck1",
			0.5,
			"Tongue1",
			1,
			"Tongue2",
			1
		};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};
};
