class CfgPatches
{
	class armst_zahvat_anim
	{
		units[]={};
		weapons[]={};
		requiredVersion=1.02;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR",
			"A3_Characters_F",
			"A3_Sounds_F",
			"A3_Data_F",
			"A3_Sounds_F",
			"A3_Anims_F"
		};
	};
};
class DefaultEventhandlers;
class CfgMovesAnimalsBase
{
	class Default
	{
		actions="";
		access=3;
		file="";
		looped=1;
		speed=0.5;
		disableWeapons=1;
		enableOptics=0;
		disableWeaponsLong=1;
		showWeaponAim=0;
		enableMissile=0;
		enableBinocular=0;
		showItemInHand=0;
		showItemInRightHand=0;
		showHandGun=0;
		onLandBeg=0;
		onLandEnd=0;
		onLadder=0;
		canPullTrigger=1;
		duty=-0.50999999;
		predictSpeedCoef=1;
		visibleSize=1;
		aimPrecision=1;
		relSpeedMin=1;
		relSpeedMax=1;
		soundEnabled=0;
		controlHead=0;
		headBobMode=0;
		headBobStrength=0;
		soundOverride="";
		soundEdge[]={0.5,1};
		terminal=0;
		limitGunMovement=1;
		variantsPlayer[]={};
		variantsAI[]=
		{
			""
		};
		equivalentTo="";
		connectAs="";
		variantAfter[]={5,10,20};
		connectFrom[]={};
		connectTo[]={};
		interpolateWith[]={};
		interpolateTo[]={};
		interpolateFrom[]={};
		aiming="aimingNo";
		leaning="aimingNo";
		untiltWeapon="aimingNo";
		aimingBody="aimingUpDefault";
		legs="legsNo";
		head="headDefault";
		leaningFactorBeg=0;
		leaningFactorEnd=0;
		leaningFactorZeroPoint=-1;
		leaningCorrectionAngleBeg=0;
		leaningCorrectionAngleEnd=0;
		interpolationSpeed=6;
		interpolationRestart=0;
		collisionShape="ca\animals2\data\geom\basicColide.p3d";
		hasCollShapeSafe=0;
		collisionShapeSafe="";
		boundingSphere=1;
		enableDirectControl=1;
		enableAutoActions=0;
		leftHandIKBeg=0;
		leftHandIKEnd=0;
		rightHandIKBeg=0;
		rightHandIKEnd=0;
		weaponIK=0;
		preload=0;
		walkcycles=1;
		forceAim=0;
		rightHandIKCurve[]={};
		leftHandIKCurve[]={};
	};
	class StandBase: Default
	{
		aiming="aimingDefault";
		disableWeapons=1;
		canReload=1;
		weaponLowered=0;
		weaponObstructed=0;
		canBlendStep=1;
		useIdles=1;
		adjstance="m";
		leaningFactorBeg=1;
		leaningFactorEnd=1;
	};
	class DefaultDie: Default
	{
		aiming="aimingNo";
		legs="legsNo";
		head="headNo";
		disableWeapons=1;
		canReload=1;
		weaponLowered=0;
		weaponObstructed=0;
		canBlendStep=1;
		useIdles=1;
		adjstance="m";
		interpolationRestart=1;
		soundOverride="fallbody";
		soundEdge[]={0.44999999};
		soundEnabled=1;
	};
	class ManActions
	{
		AdjustF="zahvat_StopV2";
		AdjustB="zahvat_StopV2";
		AdjustL="zahvat_StopV2";
		AdjustR="zahvat_StopV2";
		AdjustLF="zahvat_StopV2";
		AdjustLB="zahvat_StopV2";
		AdjustRB="zahvat_StopV2";
		AdjustRF="zahvat_StopV2";
		dooraction="zahvat_StopV2";
		GestureLegPush="zahvat_StopV2";
		agonyStart="zahvat_StopV2";
		agonyStop="zahvat_StopV2";
		medicStop="zahvat_StopV2";
		medicStart="zahvat_StopV2";
		medicStartUp="zahvat_StopV2";
		medicStartRightSide="zahvat_StopV2";
		GestureAgonyCargo="zahvat_StopV2";
		grabCarry="zahvat_StopV2";
		grabCarried="zahvat_StopV2";
		grabDrag="zahvat_StopV2";
		grabDragged="zahvat_StopV2";
		carriedStill="zahvat_StopV2";
		released="zahvat_StopV2";
		releasedBad="zahvat_StopV2";
		Stop="zahvat_StopV2";
		StopRelaxed="zahvat_StopV2";
		TurnL="zahvat_StopV2";
		TurnR="zahvat_StopV2";
		TurnLRelaxed="zahvat_StopV2";
		TurnRRelaxed="zahvat_StopV2";
		ReloadMagazine="zahvat_StopV2";
		reloadGM6="zahvat_StopV2";
		ReloadMGun="zahvat_StopV2";
		ReloadRPG="zahvat_StopV2";
		ReloadMortar="zahvat_StopV2";
		ThrowPrepare="zahvat_StopV2";
		ThrowGrenade="zahvat_StopV2";
		WalkF="zahvat_StopV2";
		WalkLF="zahvat_StopV2";
		WalkRF="zahvat_StopV2";
		WalkL="zahvat_StopV2";
		WalkR="zahvat_StopV2";
		WalkLB="zahvat_StopV2";
		WalkRB="zahvat_StopV2";
		WalkB="zahvat_StopV2";
		PlayerWalkF="zahvat_StopV2";
		PlayerWalkLF="zahvat_StopV2";
		PlayerWalkRF="zahvat_StopV2";
		PlayerWalkL="zahvat_StopV2";
		PlayerWalkR="zahvat_StopV2";
		PlayerWalkLB="zahvat_StopV2";
		PlayerWalkRB="zahvat_StopV2";
		PlayerWalkB="zahvat_StopV2";
		SlowF="zahvat_StopV2";
		SlowLF="zahvat_StopV2";
		SlowRF="zahvat_StopV2";
		SlowL="zahvat_StopV2";
		SlowR="zahvat_StopV2";
		SlowLB="zahvat_StopV2";
		SlowRB="zahvat_StopV2";
		SlowB="zahvat_StopV2";
		PlayerSlowF="zahvat_StopV2";
		PlayerSlowLF="zahvat_StopV2";
		PlayerSlowRF="zahvat_StopV2";
		PlayerSlowL="zahvat_StopV2";
		PlayerSlowR="zahvat_StopV2";
		PlayerSlowLB="zahvat_StopV2";
		PlayerSlowRB="zahvat_StopV2";
		PlayerSlowB="zahvat_StopV2";
		FastF="zahvat_StopV2";
		FastLF="zahvat_StopV2";
		FastRF="zahvat_StopV2";
		FastL="zahvat_StopV2";
		FastR="zahvat_StopV2";
		FastLB="zahvat_StopV2";
		FastRB="zahvat_StopV2";
		FastB="zahvat_StopV2";
		TactF="zahvat_StopV2";
		TactLF="zahvat_StopV2";
		TactRF="zahvat_StopV2";
		TactL="zahvat_StopV2";
		TactR="zahvat_StopV2";
		TactLB="zahvat_StopV2";
		TactRB="zahvat_StopV2";
		TactB="zahvat_StopV2";
		PlayerTactF="zahvat_StopV2";
		PlayerTactLF="zahvat_StopV2";
		PlayerTactRF="zahvat_StopV2";
		PlayerTactL="zahvat_StopV2";
		PlayerTactR="zahvat_StopV2";
		PlayerTactLB="zahvat_StopV2";
		PlayerTactRB="zahvat_StopV2";
		PlayerTactB="zahvat_StopV2";
		EvasiveLeft="zahvat_StopV2";
		EvasiveRight="zahvat_StopV2";
		startSwim="zahvat_StopV2";
		surfaceSwim="zahvat_StopV2";
		bottomSwim="zahvat_StopV2";
		StopSwim="zahvat_StopV2";
		startDive="zahvat_StopV2";
		SurfaceDive="zahvat_StopV2";
		BottomDive="zahvat_StopV2";
		StopDive="zahvat_StopV2";
		Down="zahvat_StopV2";
		Up="zahvat_StopV2";
		PlayerStand="zahvat_StopV2";
		PlayerCrouch="zahvat_StopV2";
		PlayerProne="zahvat_StopV2";
		Lying="zahvat_StopV2";
		Stand="zahvat_StopV2";
		Combat="zahvat_StopV2";
		Crouch="zahvat_StopV2";
		CanNotMove="zahvat_StopV2";
		Civil="zahvat_StopV2";
		CivilLying="zahvat_StopV2";
		FireNotPossible="zahvat_StopV2";
		Die="zahvat_StopV2";
		Unconscious="zahvat_StopV2";
		WeaponOn="zahvat_StopV2";
		WeaponOff="zahvat_StopV2";
		Default="zahvat_StopV2";
		JumpOff="zahvat_StopV2";
		StrokeFist="zahvat_StopV2";
		StrokeGun="zahvat_StopV2";
		SitDown="zahvat_StopV2";
		Salute="zahvat_StopV2";
		saluteOff="zahvat_StopV2";
		GetOver="zahvat_StopV2";
		Diary="zahvat_StopV2";
		Surrender="zahvat_StopV2";
		Gear="zahvat_StopV2";
		BinocOn="zahvat_StopV2";
		BinocOff="zahvat_StopV2";
		PutDown="zahvat_StopV2";
		PutDownEnd="zahvat_StopV2";
		Medic="zahvat_StopV2";
		MedicOther="zahvat_StopV2";
		Treated="zahvat_StopV2";
		LadderOnDown="zahvat_StopV2";
		LadderOnUp="zahvat_StopV2";
		LadderOff="zahvat_StopV2";
		LadderOffTop="zahvat_StopV2";
		LadderOffBottom="zahvat_StopV2";
		GetInLow="zahvat_StopV2";
		GetInMedium="zahvat_StopV2";
		GetInHigh="zahvat_StopV2";
		GetInVertical="zahvat_StopV2";
		GetInSDV="zahvat_StopV2";
		GetInHeli_Attack_01Pilot="zahvat_StopV2";
		GetInHeli_Attack_01Gunner="zahvat_StopV2";
		GetInHelicopterCargo="zahvat_StopV2";
		GetInMRAP_01="zahvat_StopV2";
		GetInMRAP_01_cargo="zahvat_StopV2";
		GetOutMRAP_01="zahvat_StopV2";
		GetOutMRAP_01_cargo="zahvat_StopV2";
		GetOutHelicopterCargo="zahvat_StopV2";
		GetOutLow="zahvat_StopV2";
		GetOutMedium="zahvat_StopV2";
		GetOutHigh="zahvat_StopV2";
		GetOutHighZamak="zahvat_StopV2";
		GetOutHighHemtt="zahvat_StopV2";
		GetOutSDV="zahvat_StopV2";
		GetOutHeli_Attack_01Pilot="zahvat_StopV2";
		GetOutHeli_Attack_01Gunner="zahvat_StopV2";
		GetInBoat="zahvat_StopV2";
		GetOutBoat="zahvat_StopV2";
		TakeFlag="zahvat_StopV2";
		HandGunOn="zahvat_StopV2";
		gestureAttack="zahvat_StopV2";
		gestureGo="zahvat_StopV2";
		gestureGoB="zahvat_StopV2";
		gestureFreeze="zahvat_StopV2";
		gesturePoint="zahvat_StopV2";
		gestureCeaseFire="zahvat_StopV2";
		gestureCover="zahvat_StopV2";
		gestureUp="zahvat_StopV2";
		gestureNo="zahvat_StopV2";
		gestureYes="zahvat_StopV2";
		gestureFollow="zahvat_StopV2";
		gestureAdvance="zahvat_StopV2";
		gestureHi="zahvat_StopV2";
		gestureHiB="zahvat_StopV2";
		gestureHiC="zahvat_StopV2";
		gestureNod="zahvat_StopV2";
		GestureSpasm0="zahvat_StopV2";
		GestureSpasm1="zahvat_StopV2";
		GestureSpasm2="zahvat_StopV2";
		GestureSpasm3="zahvat_StopV2";
		GestureSpasm4="zahvat_StopV2";
		GestureSpasm5="zahvat_StopV2";
		GestureSpasm6="zahvat_StopV2";
		GestureSpasm0weak="zahvat_StopV2";
		GestureSpasm1weak="zahvat_StopV2";
		GestureSpasm2weak="zahvat_StopV2";
		GestureSpasm3weak="zahvat_StopV2";
		GestureSpasm4weak="zahvat_StopV2";
		GestureSpasm5weak="zahvat_StopV2";
		GestureSpasm6weak="zahvat_StopV2";
		GestureReloadMX="zahvat_StopV2";
		GestureReloadMXCompact="zahvat_StopV2";
		GestureReloadMXSniper="zahvat_StopV2";
		GestureReloadMk20="zahvat_StopV2";
		GestureReloadMk20UGL="zahvat_StopV2";
		GestureReloadMXUGL="zahvat_StopV2";
		GestureReloadTRG="zahvat_StopV2";
		GestureReloadTRGUGL="zahvat_StopV2";
		GestureReloadKatiba="zahvat_StopV2";
		GestureReloadKatibaUGL="zahvat_StopV2";
		GestureReloadM200="zahvat_StopV2";
		GestureReloadLRR="zahvat_StopV2";
		GestureReloadEBR="zahvat_StopV2";
		GestureReloadM4SSAS="zahvat_StopV2";
		GestureReloadSMG_02="zahvat_StopV2";
		GestureReloadSMG_03="zahvat_StopV2";
		GestureReloadPistol="zahvat_StopV2";
		GestureReloadPistolHeavy02="zahvat_StopV2";
		GestureReloadFlaregun="zahvat_StopV2";
		GestureReloadSMG_01="zahvat_StopV2";
		GestureReloadSDAR="zahvat_StopV2";
		GestureReloadDMR="zahvat_StopV2";
		GestureReloadDMR02="zahvat_StopV2";
		GestureReloadDMR03="zahvat_StopV2";
		GestureReloadDMR04="zahvat_StopV2";
		GestureReloadDMR05="zahvat_StopV2";
		GestureReloadDMR06="zahvat_StopV2";
		GestureReloadMMG01="zahvat_StopV2";
		GestureReloadMMG02="zahvat_StopV2";
		MountOptic="zahvat_StopV2";
		DismountOptic="zahvat_StopV2";
		MountSide="zahvat_StopV2";
		DismountSide="zahvat_StopV2";
		GestureMountMuzzle="zahvat_StopV2";
		GestureDismountMuzzle="zahvat_StopV2";
		healedStart="zahvat_StopV2";
		healedStop="zahvat_StopV2";
		TestDriver="zahvat_StopV2";
		TestDriverOut="zahvat_StopV2";
		TestGunner="zahvat_StopV2";
		Relax="zahvat_StopV2";
		swimUp="zahvat_StopV2";
		swimDown="zahvat_StopV2";
		StartFreefall="zahvat_StopV2";
		PrimaryWeapon="zahvat_StopV2";
		SecondaryWeapon="zahvat_StopV2";
		Binoculars="zahvat_StopV2";
		FDStart="zahvat_StopV2";
		Obstructed="zahvat_StopV2";
	};
	class BlendAnims
	{
		aimingDefault[]={};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]={};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};
	collisionVertexPattern[]=
	{
		"1a",
		"2a",
		"3a",
		"4a",
		"5a",
		"6a",
		"7a",
		"8a",
		"9a",
		"10a",
		"11a",
		"12a",
		"13a",
		"14a",
		"15a",
		"16a",
		"17a",
		"18a",
		"19a",
		"20a",
		"21a",
		"22a",
		"23a",
		"24a",
		"25a",
		"26a",
		"27a",
		"28a",
		"29a",
		"30a",
		"31a",
		"32a",
		"33a",
		"34a"
	};
	collisionGeomCompPattern[]={1};
};
class CfgMoveszahvat: CfgMovesAnimalsBase
{
	primaryActionMaps[]=
	{
		"zahvatActions",
		"NoActions"
	};
	skeletonName="ZahvatSkeleton";
	gestures="CfgGesturesMale";
	extended="CfgExtendedAnimation";
	class States
	{
		class zahvat_Stop: StandBase
		{
			actions="zahvatActions";
			duty=-1;
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			variantsAI[]={};
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			variantAfter[]={0,2,3};
			speed=0.25;
			relSpeedMin=0.69999999;
			relSpeedMax=1.1;
			looped=1;
			collisionShape="A3\anims_f\Data\Geom\Sdr\Perc_Wnon.p3d";
			ConnectTo[]=
			{
				"zahvat_TurnR",
				0.1,
				"zahvat_TurnL",
				0.1,
				"zahvat_Sprint",
				0.02,
				"zahvat_Run",
				0.02,
				"zahvat_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat_TurnR",
				0.1,
				"zahvat_Die",
				0.02,
				"zahvat_TurnL",
				0.1,
				"zahvat_Sprint",
				0.02,
				"zahvat_Run",
				0.02,
				"zahvat_Walk",
				0.2
			};
		};
		class zahvat_angry: zahvat_Stop
		{
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
			looped=1;
			ConnectTo[]=
			{
				"zahvat_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat_Stop",
				0.02
			};
		};
		class zahvat_attack1: zahvat_Stop
		{
			file="\armst\armst_char\char_mut\zahvat\anim\attack.rtm";
			speed=0.25;
		};
		class zahvat_attack2: zahvat_Stop
		{
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat_attack3: zahvat_Stop
		{
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat_attack4: zahvat_Stop
		{
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat_TurnL: zahvat_Stop
		{
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
			ConnectTo[]=
			{
				"zahvat_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat_Stop",
				0.1
			};
		};
		class zahvat_TurnR: zahvat_TurnL
		{
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
			ConnectTo[]=
			{
				"zahvat_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat_Stop",
				0.1
			};
		};
		class zahvat_StopV1: zahvat_Stop
		{
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
			looped=1;
			ConnectTo[]=
			{
				"zahvat_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat_Stop",
				0.02
			};
		};
		class zahvat_Sprint: zahvat_Stop
		{
			actions="zahvatSprint";
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
			duty=0.5;
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			ConnectTo[]=
			{
				"zahvat_Stop",
				0.02,
				"zahvat_Run",
				0.02,
				"zahvat_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat_Die",
				0.02,
				"zahvat_Stop",
				0.02,
				"zahvat_Run",
				0.02,
				"zahvat_Walk",
				0.2
			};
		};
		class zahvat_Run: zahvat_Stop
		{
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
			duty=-0.5;
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			ConnectTo[]=
			{
				"zahvat_Stop",
				0.02,
				"zahvat_Sprint",
				0.02,
				"zahvat_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat_Die",
				0.02,
				"zahvat_Stop",
				0.02,
				"zahvat_Sprint",
				0.02,
				"zahvat_Walk",
				0.2
			};
		};
		class zahvat_Walk: zahvat_Stop
		{
			duty=-0.69999999;
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			ConnectTo[]=
			{
				"zahvat_Stop",
				0.2,
				"zahvat_Sprint",
				0.2,
				"zahvat_Run",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat_Die",
				0.02,
				"zahvat_Stop",
				0.2,
				"zahvat_Sprint",
				0.2,
				"zahvat_Run",
				0.2
			};
		};
		class zahvat_Die: DefaultDie
		{
			file="\armst\armst_char\char_mut\zahvat\anim\idle.rtm";
			speed=0.25;
			looped=0;
			onLandBeg=1;
			onLandEnd=1;
			soundEnabled=0;
			terminal=1;
			ragdoll=1;
			headBobMode=4;
			headBobStrength=-1;
			disableWeapons=1;
			disableWeaponsLong=1;
		};
	};
	class Actions
	{
		class NoActions: ManActions
		{
			turnSpeed=8;
			limitFast=5.5;
			useFastMove=0;
			upDegree=0;
			stance="zahvat_Stop";
		};
		class zahvatActions: NoActions
		{
			Stop="zahvat_Stop";
			StopRelaxed="zahvat_Stop";
			TurnL="zahvat_Stop";
			TurnR="zahvat_Stop";
			TurnLRelaxed="zahvat_Stop";
			TurnRRelaxed="zahvat_Stop";
			Default="zahvat_Stop";
			JumpOff="zahvat_Stop";
			WalkF="zahvat_Stop";
			SlowF="zahvat_Stop";
			FastF="zahvat_Stop";
			EvasiveForward="zahvat_Stop";
			Down="zahvat_Stop";
			Up="zahvat_Stop";
			PlayerStand="zahvat_Stop";
			PlayerProne="zahvat_Stop";
			PlayerCrouch="zahvat_Stop";
			Crouch="zahvat_Stop";
			Lying="zahvat_Stop";
			Stand="zahvat_Stop";
			Combat="zahvat_Stop";
			CanNotMove="zahvat_Stop";
			Civil="zahvat_Stop";
			CivilLying="zahvat_Stop";
			FireNotPossible="zahvat_Stop";
			Die="zahvat_Die";
			turnSpeed=1;
			limitFast=1.5;
			useFastMove=0;
			upDegree="ManPosNoWeapon";
			StartSwim="zahvat_Die";
		};
		class zahvatSprint: zahvatActions
		{
			Die="zahvat_Die";
			TurnL="zahvat_Stop";
			TurnR="zahvat_Stop";
			TurnLRelaxed="zahvat_Stop";
			TurnRRelaxed="zahvat_Stop";
			turnSpeed=10;
			limitFast=1.5;
			useFastMove=1;
		};
	};
	class Interpolations
	{
	};
	transitionsInterpolated[]={};
	transitionsSimple[]={};
	transitionsDisabled[]={};
	class BlendAnims: BlendAnims
	{
		aimingDefault[]={};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]={};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};
};
