class CfgPatches
{
	class armst_zahvat3_anim
	{
		units[]={};
		weapons[]={};
		requiredVersion=1.02;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR",
			"A3_Characters_F",
			"A3_Sounds_F",
			"A3_Data_F",
			"A3_Sounds_F",
			"A3_Anims_F"
		};
	};
};
class DefaultEventhandlers;
class CfgMovesAnimalsBase
{
	class Default
	{
		actions="";
		access=3;
		file="";
		looped=1;
		speed=0.5;
		disableWeapons=1;
		enableOptics=0;
		disableWeaponsLong=1;
		showWeaponAim=0;
		enableMissile=0;
		enableBinocular=0;
		showItemInHand=0;
		showItemInRightHand=0;
		showHandGun=0;
		onLandBeg=0;
		onLandEnd=0;
		onLadder=0;
		canPullTrigger=1;
		duty=-0.50999999;
		predictSpeedCoef=1;
		visibleSize=1;
		aimPrecision=1;
		relSpeedMin=1;
		relSpeedMax=1;
		soundEnabled=0;
		controlHead=0;
		headBobMode=0;
		headBobStrength=0;
		soundOverride="";
		soundEdge[]={0.5,1};
		terminal=0;
		limitGunMovement=1;
		variantsPlayer[]={};
		variantsAI[]=
		{
			""
		};
		equivalentTo="";
		connectAs="";
		variantAfter[]={5,10,20};
		connectFrom[]={};
		connectTo[]={};
		interpolateWith[]={};
		interpolateTo[]={};
		interpolateFrom[]={};
		aiming="aimingNo";
		leaning="aimingNo";
		untiltWeapon="aimingNo";
		aimingBody="aimingUpDefault";
		legs="legsNo";
		head="headDefault";
		leaningFactorBeg=0;
		leaningFactorEnd=0;
		leaningFactorZeroPoint=-1;
		leaningCorrectionAngleBeg=0;
		leaningCorrectionAngleEnd=0;
		interpolationSpeed=6;
		interpolationRestart=0;
		collisionShape="ca\animals2\data\geom\basicColide.p3d";
		hasCollShapeSafe=0;
		collisionShapeSafe="";
		boundingSphere=1;
		enableDirectControl=1;
		enableAutoActions=0;
		leftHandIKBeg=0;
		leftHandIKEnd=0;
		rightHandIKBeg=0;
		rightHandIKEnd=0;
		weaponIK=0;
		preload=0;
		walkcycles=1;
		forceAim=0;
		rightHandIKCurve[]={};
		leftHandIKCurve[]={};
	};
	class StandBase: Default
	{
		aiming="aimingDefault";
		disableWeapons=1;
		canReload=1;
		weaponLowered=0;
		weaponObstructed=0;
		canBlendStep=1;
		useIdles=1;
		adjstance="m";
		leaningFactorBeg=1;
		leaningFactorEnd=1;
	};
	class DefaultDie: Default
	{
		aiming="aimingNo";
		legs="legsNo";
		head="headNo";
		disableWeapons=1;
		canReload=1;
		weaponLowered=0;
		weaponObstructed=0;
		canBlendStep=1;
		useIdles=1;
		adjstance="m";
		interpolationRestart=1;
		soundOverride="fallbody";
		soundEdge[]={0.44999999};
		soundEnabled=1;
	};
	class ManActions
	{
		AdjustF="zahvat3_StopV2";
		AdjustB="zahvat3_StopV2";
		AdjustL="zahvat3_StopV2";
		AdjustR="zahvat3_StopV2";
		AdjustLF="zahvat3_StopV2";
		AdjustLB="zahvat3_StopV2";
		AdjustRB="zahvat3_StopV2";
		AdjustRF="zahvat3_StopV2";
		dooraction="zahvat3_StopV2";
		GestureLegPush="zahvat3_StopV2";
		agonyStart="zahvat3_StopV2";
		agonyStop="zahvat3_StopV2";
		medicStop="zahvat3_StopV2";
		medicStart="zahvat3_StopV2";
		medicStartUp="zahvat3_StopV2";
		medicStartRightSide="zahvat3_StopV2";
		GestureAgonyCargo="zahvat3_StopV2";
		grabCarry="zahvat3_StopV2";
		grabCarried="zahvat3_StopV2";
		grabDrag="zahvat3_StopV2";
		grabDragged="zahvat3_StopV2";
		carriedStill="zahvat3_StopV2";
		released="zahvat3_StopV2";
		releasedBad="zahvat3_StopV2";
		Stop="zahvat3_StopV2";
		StopRelaxed="zahvat3_StopV2";
		TurnL="zahvat3_StopV2";
		TurnR="zahvat3_StopV2";
		TurnLRelaxed="zahvat3_StopV2";
		TurnRRelaxed="zahvat3_StopV2";
		ReloadMagazine="zahvat3_StopV2";
		reloadGM6="zahvat3_StopV2";
		ReloadMGun="zahvat3_StopV2";
		ReloadRPG="zahvat3_StopV2";
		ReloadMortar="zahvat3_StopV2";
		ThrowPrepare="zahvat3_StopV2";
		ThrowGrenade="zahvat3_StopV2";
		WalkF="zahvat3_StopV2";
		WalkLF="zahvat3_StopV2";
		WalkRF="zahvat3_StopV2";
		WalkL="zahvat3_StopV2";
		WalkR="zahvat3_StopV2";
		WalkLB="zahvat3_StopV2";
		WalkRB="zahvat3_StopV2";
		WalkB="zahvat3_StopV2";
		PlayerWalkF="zahvat3_StopV2";
		PlayerWalkLF="zahvat3_StopV2";
		PlayerWalkRF="zahvat3_StopV2";
		PlayerWalkL="zahvat3_StopV2";
		PlayerWalkR="zahvat3_StopV2";
		PlayerWalkLB="zahvat3_StopV2";
		PlayerWalkRB="zahvat3_StopV2";
		PlayerWalkB="zahvat3_StopV2";
		SlowF="zahvat3_StopV2";
		SlowLF="zahvat3_StopV2";
		SlowRF="zahvat3_StopV2";
		SlowL="zahvat3_StopV2";
		SlowR="zahvat3_StopV2";
		SlowLB="zahvat3_StopV2";
		SlowRB="zahvat3_StopV2";
		SlowB="zahvat3_StopV2";
		PlayerSlowF="zahvat3_StopV2";
		PlayerSlowLF="zahvat3_StopV2";
		PlayerSlowRF="zahvat3_StopV2";
		PlayerSlowL="zahvat3_StopV2";
		PlayerSlowR="zahvat3_StopV2";
		PlayerSlowLB="zahvat3_StopV2";
		PlayerSlowRB="zahvat3_StopV2";
		PlayerSlowB="zahvat3_StopV2";
		FastF="zahvat3_StopV2";
		FastLF="zahvat3_StopV2";
		FastRF="zahvat3_StopV2";
		FastL="zahvat3_StopV2";
		FastR="zahvat3_StopV2";
		FastLB="zahvat3_StopV2";
		FastRB="zahvat3_StopV2";
		FastB="zahvat3_StopV2";
		TactF="zahvat3_StopV2";
		TactLF="zahvat3_StopV2";
		TactRF="zahvat3_StopV2";
		TactL="zahvat3_StopV2";
		TactR="zahvat3_StopV2";
		TactLB="zahvat3_StopV2";
		TactRB="zahvat3_StopV2";
		TactB="zahvat3_StopV2";
		PlayerTactF="zahvat3_StopV2";
		PlayerTactLF="zahvat3_StopV2";
		PlayerTactRF="zahvat3_StopV2";
		PlayerTactL="zahvat3_StopV2";
		PlayerTactR="zahvat3_StopV2";
		PlayerTactLB="zahvat3_StopV2";
		PlayerTactRB="zahvat3_StopV2";
		PlayerTactB="zahvat3_StopV2";
		EvasiveLeft="zahvat3_StopV2";
		EvasiveRight="zahvat3_StopV2";
		startSwim="zahvat3_StopV2";
		surfaceSwim="zahvat3_StopV2";
		bottomSwim="zahvat3_StopV2";
		StopSwim="zahvat3_StopV2";
		startDive="zahvat3_StopV2";
		SurfaceDive="zahvat3_StopV2";
		BottomDive="zahvat3_StopV2";
		StopDive="zahvat3_StopV2";
		Down="zahvat3_StopV2";
		Up="zahvat3_StopV2";
		PlayerStand="zahvat3_StopV2";
		PlayerCrouch="zahvat3_StopV2";
		PlayerProne="zahvat3_StopV2";
		Lying="zahvat3_StopV2";
		Stand="zahvat3_StopV2";
		Combat="zahvat3_StopV2";
		Crouch="zahvat3_StopV2";
		CanNotMove="zahvat3_StopV2";
		Civil="zahvat3_StopV2";
		CivilLying="zahvat3_StopV2";
		FireNotPossible="zahvat3_StopV2";
		Die="zahvat3_StopV2";
		Unconscious="zahvat3_StopV2";
		WeaponOn="zahvat3_StopV2";
		WeaponOff="zahvat3_StopV2";
		Default="zahvat3_StopV2";
		JumpOff="zahvat3_StopV2";
		StrokeFist="zahvat3_StopV2";
		StrokeGun="zahvat3_StopV2";
		SitDown="zahvat3_StopV2";
		Salute="zahvat3_StopV2";
		saluteOff="zahvat3_StopV2";
		GetOver="zahvat3_StopV2";
		Diary="zahvat3_StopV2";
		Surrender="zahvat3_StopV2";
		Gear="zahvat3_StopV2";
		BinocOn="zahvat3_StopV2";
		BinocOff="zahvat3_StopV2";
		PutDown="zahvat3_StopV2";
		PutDownEnd="zahvat3_StopV2";
		Medic="zahvat3_StopV2";
		MedicOther="zahvat3_StopV2";
		Treated="zahvat3_StopV2";
		LadderOnDown="zahvat3_StopV2";
		LadderOnUp="zahvat3_StopV2";
		LadderOff="zahvat3_StopV2";
		LadderOffTop="zahvat3_StopV2";
		LadderOffBottom="zahvat3_StopV2";
		GetInLow="zahvat3_StopV2";
		GetInMedium="zahvat3_StopV2";
		GetInHigh="zahvat3_StopV2";
		GetInVertical="zahvat3_StopV2";
		GetInSDV="zahvat3_StopV2";
		GetInHeli_Attack_01Pilot="zahvat3_StopV2";
		GetInHeli_Attack_01Gunner="zahvat3_StopV2";
		GetInHelicopterCargo="zahvat3_StopV2";
		GetInMRAP_01="zahvat3_StopV2";
		GetInMRAP_01_cargo="zahvat3_StopV2";
		GetOutMRAP_01="zahvat3_StopV2";
		GetOutMRAP_01_cargo="zahvat3_StopV2";
		GetOutHelicopterCargo="zahvat3_StopV2";
		GetOutLow="zahvat3_StopV2";
		GetOutMedium="zahvat3_StopV2";
		GetOutHigh="zahvat3_StopV2";
		GetOutHighZamak="zahvat3_StopV2";
		GetOutHighHemtt="zahvat3_StopV2";
		GetOutSDV="zahvat3_StopV2";
		GetOutHeli_Attack_01Pilot="zahvat3_StopV2";
		GetOutHeli_Attack_01Gunner="zahvat3_StopV2";
		GetInBoat="zahvat3_StopV2";
		GetOutBoat="zahvat3_StopV2";
		TakeFlag="zahvat3_StopV2";
		HandGunOn="zahvat3_StopV2";
		gestureAttack="zahvat3_StopV2";
		gestureGo="zahvat3_StopV2";
		gestureGoB="zahvat3_StopV2";
		gestureFreeze="zahvat3_StopV2";
		gesturePoint="zahvat3_StopV2";
		gestureCeaseFire="zahvat3_StopV2";
		gestureCover="zahvat3_StopV2";
		gestureUp="zahvat3_StopV2";
		gestureNo="zahvat3_StopV2";
		gestureYes="zahvat3_StopV2";
		gestureFollow="zahvat3_StopV2";
		gestureAdvance="zahvat3_StopV2";
		gestureHi="zahvat3_StopV2";
		gestureHiB="zahvat3_StopV2";
		gestureHiC="zahvat3_StopV2";
		gestureNod="zahvat3_StopV2";
		GestureSpasm0="zahvat3_StopV2";
		GestureSpasm1="zahvat3_StopV2";
		GestureSpasm2="zahvat3_StopV2";
		GestureSpasm3="zahvat3_StopV2";
		GestureSpasm4="zahvat3_StopV2";
		GestureSpasm5="zahvat3_StopV2";
		GestureSpasm6="zahvat3_StopV2";
		GestureSpasm0weak="zahvat3_StopV2";
		GestureSpasm1weak="zahvat3_StopV2";
		GestureSpasm2weak="zahvat3_StopV2";
		GestureSpasm3weak="zahvat3_StopV2";
		GestureSpasm4weak="zahvat3_StopV2";
		GestureSpasm5weak="zahvat3_StopV2";
		GestureSpasm6weak="zahvat3_StopV2";
		GestureReloadMX="zahvat3_StopV2";
		GestureReloadMXCompact="zahvat3_StopV2";
		GestureReloadMXSniper="zahvat3_StopV2";
		GestureReloadMk20="zahvat3_StopV2";
		GestureReloadMk20UGL="zahvat3_StopV2";
		GestureReloadMXUGL="zahvat3_StopV2";
		GestureReloadTRG="zahvat3_StopV2";
		GestureReloadTRGUGL="zahvat3_StopV2";
		GestureReloadKatiba="zahvat3_StopV2";
		GestureReloadKatibaUGL="zahvat3_StopV2";
		GestureReloadM200="zahvat3_StopV2";
		GestureReloadLRR="zahvat3_StopV2";
		GestureReloadEBR="zahvat3_StopV2";
		GestureReloadM4SSAS="zahvat3_StopV2";
		GestureReloadSMG_02="zahvat3_StopV2";
		GestureReloadSMG_03="zahvat3_StopV2";
		GestureReloadPistol="zahvat3_StopV2";
		GestureReloadPistolHeavy02="zahvat3_StopV2";
		GestureReloadFlaregun="zahvat3_StopV2";
		GestureReloadSMG_01="zahvat3_StopV2";
		GestureReloadSDAR="zahvat3_StopV2";
		GestureReloadDMR="zahvat3_StopV2";
		GestureReloadDMR02="zahvat3_StopV2";
		GestureReloadDMR03="zahvat3_StopV2";
		GestureReloadDMR04="zahvat3_StopV2";
		GestureReloadDMR05="zahvat3_StopV2";
		GestureReloadDMR06="zahvat3_StopV2";
		GestureReloadMMG01="zahvat3_StopV2";
		GestureReloadMMG02="zahvat3_StopV2";
		MountOptic="zahvat3_StopV2";
		DismountOptic="zahvat3_StopV2";
		MountSide="zahvat3_StopV2";
		DismountSide="zahvat3_StopV2";
		GestureMountMuzzle="zahvat3_StopV2";
		GestureDismountMuzzle="zahvat3_StopV2";
		healedStart="zahvat3_StopV2";
		healedStop="zahvat3_StopV2";
		TestDriver="zahvat3_StopV2";
		TestDriverOut="zahvat3_StopV2";
		TestGunner="zahvat3_StopV2";
		Relax="zahvat3_StopV2";
		swimUp="zahvat3_StopV2";
		swimDown="zahvat3_StopV2";
		StartFreefall="zahvat3_StopV2";
		PrimaryWeapon="zahvat3_StopV2";
		SecondaryWeapon="zahvat3_StopV2";
		Binoculars="zahvat3_StopV2";
		FDStart="zahvat3_StopV2";
		Obstructed="zahvat3_StopV2";
	};
	class BlendAnims
	{
		aimingDefault[]={};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]={};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};
	collisionVertexPattern[]=
	{
		"1a",
		"2a",
		"3a",
		"4a",
		"5a",
		"6a",
		"7a",
		"8a",
		"9a",
		"10a",
		"11a",
		"12a",
		"13a",
		"14a",
		"15a",
		"16a",
		"17a",
		"18a",
		"19a",
		"20a",
		"21a",
		"22a",
		"23a",
		"24a",
		"25a",
		"26a",
		"27a",
		"28a",
		"29a",
		"30a",
		"31a",
		"32a",
		"33a",
		"34a"
	};
	collisionGeomCompPattern[]={1};
};
class CfgMoveszahvat3: CfgMovesAnimalsBase
{
	primaryActionMaps[]=
	{
		"zahvat3Actions",
		"NoActions"
	};
	skeletonName="Zahvat3Skeleton";
	gestures="CfgGesturesMale";
	extended="CfgExtendedAnimation";
	class States
	{
		class zahvat3_Stop: StandBase
		{
			actions="zahvat3Actions";
			duty=-1;
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			variantsAI[]={};
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			variantAfter[]={0,2,3};
			speed=0.25;
			relSpeedMin=0.69999999;
			relSpeedMax=1.1;
			looped=1;
			collisionShape="A3\anims_f\Data\Geom\Sdr\Perc_Wnon.p3d";
			ConnectTo[]=
			{
				"zahvat3_TurnR",
				0.1,
				"zahvat3_TurnL",
				0.1,
				"zahvat3_Sprint",
				0.02,
				"zahvat3_Run",
				0.02,
				"zahvat3_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat3_TurnR",
				0.1,
				"zahvat3_Die",
				0.02,
				"zahvat3_TurnL",
				0.1,
				"zahvat3_Sprint",
				0.02,
				"zahvat3_Run",
				0.02,
				"zahvat3_Walk",
				0.2
			};
		};
		class zahvat3_angry: zahvat3_Stop
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
			looped=1;
			ConnectTo[]=
			{
				"zahvat3_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat3_Stop",
				0.02
			};
		};
		class zahvat3_attack1: zahvat3_Stop
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat3_attack2: zahvat3_Stop
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat3_attack3: zahvat3_Stop
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat3_attack4: zahvat3_Stop
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
		};
		class zahvat3_TurnL: zahvat3_Stop
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
			ConnectTo[]=
			{
				"zahvat3_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat3_Stop",
				0.1
			};
		};
		class zahvat3_TurnR: zahvat3_TurnL
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
			ConnectTo[]=
			{
				"zahvat3_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat3_Stop",
				0.1
			};
		};
		class zahvat3_StopV1: zahvat3_Stop
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
			looped=1;
			ConnectTo[]=
			{
				"zahvat3_Stop",
				0.1
			};
			InterpolateTo[]=
			{
				"zahvat3_Stop",
				0.02
			};
		};
		class zahvat3_Sprint: zahvat3_Stop
		{
			actions="zahvat3Sprint";
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
			duty=0.5;
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			ConnectTo[]=
			{
				"zahvat3_Stop",
				0.02,
				"zahvat3_Run",
				0.02,
				"zahvat3_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat3_Die",
				0.02,
				"zahvat3_Stop",
				0.02,
				"zahvat3_Run",
				0.02,
				"zahvat3_Walk",
				0.2
			};
		};
		class zahvat3_Run: zahvat3_Stop
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
			duty=-0.5;
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			ConnectTo[]=
			{
				"zahvat3_Stop",
				0.02,
				"zahvat3_Sprint",
				0.02,
				"zahvat3_Walk",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat3_Die",
				0.02,
				"zahvat3_Stop",
				0.02,
				"zahvat3_Sprint",
				0.02,
				"zahvat3_Walk",
				0.2
			};
		};
		class zahvat3_Walk: zahvat3_Stop
		{
			duty=-0.69999999;
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
			soundOverride="sprint";
			soundEnabled=1;
			soundEdge[]={0.050000001};
			ConnectTo[]=
			{
				"zahvat3_Stop",
				0.2,
				"zahvat3_Sprint",
				0.2,
				"zahvat3_Run",
				0.2
			};
			InterpolateTo[]=
			{
				"zahvat3_Die",
				0.02,
				"zahvat3_Stop",
				0.2,
				"zahvat3_Sprint",
				0.2,
				"zahvat3_Run",
				0.2
			};
		};
		class zahvat3_Die: DefaultDie
		{
			file="\armst\armst_char\char_mut\zahvat3\anim\idle.rtm";
			speed=0.25;
			looped=0;
			onLandBeg=1;
			onLandEnd=1;
			soundEnabled=0;
			terminal=1;
			ragdoll=1;
			headBobMode=4;
			headBobStrength=-1;
			disableWeapons=1;
			disableWeaponsLong=1;
		};
	};
	class Actions
	{
		class NoActions: ManActions
		{
			turnSpeed=8;
			limitFast=5.5;
			useFastMove=0;
			upDegree=0;
			stance="zahvat3_Stop";
		};
		class zahvat3Actions: NoActions
		{
			Stop="zahvat3_Stop";
			StopRelaxed="zahvat3_Stop";
			TurnL="zahvat3_Stop";
			TurnR="zahvat3_Stop";
			TurnLRelaxed="zahvat3_Stop";
			TurnRRelaxed="zahvat3_Stop";
			Default="zahvat3_Stop";
			JumpOff="zahvat3_Stop";
			WalkF="zahvat3_Stop";
			SlowF="zahvat3_Stop";
			FastF="zahvat3_Stop";
			EvasiveForward="zahvat3_Stop";
			Down="zahvat3_Stop";
			Up="zahvat3_Stop";
			PlayerStand="zahvat3_Stop";
			PlayerProne="zahvat3_Stop";
			PlayerCrouch="zahvat3_Stop";
			Crouch="zahvat3_Stop";
			Lying="zahvat3_Stop";
			Stand="zahvat3_Stop";
			Combat="zahvat3_Stop";
			CanNotMove="zahvat3_Stop";
			Civil="zahvat3_Stop";
			CivilLying="zahvat3_Stop";
			FireNotPossible="zahvat3_Stop";
			Die="zahvat3_Die";
			turnSpeed=1;
			limitFast=1.5;
			useFastMove=0;
			upDegree="ManPosNoWeapon";
			StartSwim="zahvat3_Die";
		};
		class zahvat3Sprint: zahvat3Actions
		{
			Die="zahvat3_Die";
			TurnL="zahvat3_Stop";
			TurnR="zahvat3_Stop";
			TurnLRelaxed="zahvat3_Stop";
			TurnRRelaxed="zahvat3_Stop";
			turnSpeed=10;
			limitFast=1.5;
			useFastMove=1;
		};
	};
	class Interpolations
	{
	};
	transitionsInterpolated[]={};
	transitionsSimple[]={};
	transitionsDisabled[]={};
	class BlendAnims: BlendAnims
	{
		aimingDefault[]={};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]={};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};
};
