

	/*LOADSCREEN*/
	
	#define IDD_LOADSCREEN 1200
	#define IDC_LOADSCREEN_PIC 1202
	#define IDC_LOADSCREEN_TITLE 1201



	/*TRADE DIALOG*/
	
	#define IDD_TRADEDIALOG  1301
	#define IDC_TRADEDIALOG_BCGND  1302
	#define IDC_TRADEDIALOG_LIST  1303
	#define IDC_TRADEDIALOG_TITLE_MONEY  1304
	#define IDC_TRADEDIALOG_TITLE_GOODINFO  1305
	#define IDC_TRADEDIALOG_TITLE_GOODPRICE  1306
	#define IDC_TRADEDIALOG_TITLE_GOODDESC  1307
	#define IDC_TRADEDIALOG_TITLE_HINTCONTROL  1308
	#define IDC_TRADEDIALOG_BUTTON_FULLBUY  1309
	#define IDC_TRADEDIALOG_LIST_FULLBUY  1310



	/*TERMINAL DIALOG*/
	
	#define IDD_TERMINAL_DIALOG  1401
	#define IDC_TERMINAL_SCREEN 1402
	
	#define IDC_TERMINAL_AUTH 1403
	#define IDC_TERMINAL_AUTH_INPUT 1404
	#define IDC_TERMINAL_AUTH_CONFIRM 14041
	#define IDC_TERMINAL_AUTH_STATUS 14042
	
	#define IDC_TERMINAL_TEST 14033
	#define IDC_TERMINAL_TEST_1 14034
	
	
	#define IDC_TERMINAL_DESKTOP 1405
	#define IDC_TERMINAL_DESKTOP_NOTICE 1406
	#define IDC_TERMINAL_DESKTOP_PERSONNEL  1407
	#define IDC_TERMINAL_DESKTOP_SUMMARY  1408
	#define IDC_TERMINAL_DESKTOP_BUDGET  1409
	#define IDC_TERMINAL_DESKTOP_LOCATIONS  1410
	#define IDC_TERMINAL_DESKTOP_COMMUNICATE  1411
	#define IDC_TERMINAL_DESKTOP_ACCESS  1412
	#define IDC_TERMINAL_DESKTOP_NOTEBOOK  1413
	#define IDC_TERMINAL_DESKTOP_RESOURCES  1414
	#define IDC_TERMINAL_DESKTOP_OBJECTIVES  1415
	#define IDC_TERMINAL_DESKTOP_BASE  1416
	#define IDC_TERMINAL_DESKTOP_TRANSFER  1417
	#define IDC_TERMINAL_DESKTOP_EXIT  1418
	#define IDC_TERMINAL_DESKTOP_DESC  1419

	#define IDC_TERMINAL_APP 1420
	#define IDC_TERMINAL_APP_TITLE 1421
	#define IDC_TERMINAL_APP_REFRESH 1423
	#define IDC_TERMINAL_APP_LOADING 1424
	#define IDC_TERMINAL_APP_BACKGROUND 1425
	
	#define IDC_TERMINAL_PAGE_SUMMARY  1430
	#define IDC_TERMINAL_PAGE_SUM_ABOUTMAIN 1431
	#define IDC_TERMINAL_PAGE_SUM_LIST 1432
	
	#define IDC_TERMINAL_PAGE_PERSONNEL  1450
	#define IDC_TERMINAL_PAGE_PER_MAINMENU  1451
	#define IDC_TERMINAL_PAGE_PER_MAINMENU_BARRACK  14521
	#define IDC_TERMINAL_PAGE_PER_MAINMENU_SQUADS  14522
	#define IDC_TERMINAL_PAGE_PER_MAINMENU_RECRUITS  14523
	
	#define IDC_TERMINAL_PAGE_PER_BARRACK  14531
	#define IDC_TERMINAL_PAGE_PER_BAR_LIST  14532
	#define IDC_TERMINAL_PAGE_PER_BAR_ABOUT  14533
	#define IDC_TERMINAL_PAGE_PER_BAR_FIND_INPUT  14534
	#define IDC_TERMINAL_PAGE_PER_BAR_FIND_RESULT  14535
	#define IDC_TERMINAL_PAGE_PER_BAR_FIND_BUTTON  14536
	#define IDC_TERMINAL_PAGE_PER_BAR_EXCLUDE_BUTTON  14537
	#define IDC_TERMINAL_PAGE_PER_BAR_EXCLUDE_INPUT  14538
	
	#define IDC_TERMINAL_PAGE_PER_SQUADS  1460
	#define IDC_TERMINAL_PAGE_PER_SQD_LIST_USERS  1461
	#define IDC_TERMINAL_PAGE_PER_SQD_LIST_BUFFER  1462
	#define IDC_TERMINAL_PAGE_PER_SQD_LIST_SQUADS  1463
	#define IDC_TERMINAL_PAGE_PER_SQD_COMBO_GROUPS  1464
	#define IDC_TERMINAL_PAGE_PER_SQD_ASSIGN_BUTTON 1465
	#define IDC_TERMINAL_PAGE_PER_SQD_NAME_INPUT 1466
	#define IDC_TERMINAL_PAGE_PER_SQD_FORM_BUTTON 1467
	#define IDC_TERMINAL_PAGE_PER_SQD_DISBAND_BUTTON 1468
	#define IDC_TERMINAL_PAGE_PER_SQD_COMBO_COLORS 1469
	
	#define IDC_TERMINAL_PAGE_PER_RECRUITS  1470
	#define IDC_TERMINAL_PAGE_PER_REC_LIST  1471
	#define IDC_TERMINAL_PAGE_PER_REC_ABOUT  1472
	#define IDC_TERMINAL_PAGE_PER_REC_SHAPES  1473
	#define IDC_TERMINAL_PAGE_PER_REC_CONFIRM  1474
	#define IDC_TERMINAL_PAGE_PER_REC_REJECT  1475
	
	
	#define IDC_TERMINAL_PAGE_LOCATIONS  1480
	#define IDC_TERMINAL_PAGE_LOC_MAINMENU  1481
	#define IDC_TERMINAL_PAGE_LOC_MAINMENU_MAP  14811
	#define IDC_TERMINAL_PAGE_LOC_MAINMENU_MANAGE  14812
	
	#define IDC_TERMINAL_PAGE_LOC_MAIN  1482
	#define IDC_TERMINAL_PAGE_LOC_MAIN_LIST  14821
	#define IDC_TERMINAL_PAGE_LOC_MAIN_MAP  14822
	#define IDC_TERMINAL_PAGE_LOC_MAIN_ABOUT  14823
	
	#define IDC_TERMINAL_PAGE_LOC_MANAGE  1483
	
	#define IDC_TERMINAL_PAGE_BUDGET  1490
	#define IDC_TERMINAL_PAGE_BUD_MAINMENU  1491
	#define IDC_TERMINAL_PAGE_BUD_MAINMENU_WITHDRAW  14911
	#define IDC_TERMINAL_PAGE_BUD_MAINMENU_PLANNING  14912
	
	#define IDC_TERMINAL_PAGE_BUD_WITHDRAW  1492
	#define IDC_TERMINAL_PAGE_BUD_WDW_BUDGET  14921
	#define IDC_TERMINAL_PAGE_BUD_WDW_INPUT  14922
	#define IDC_TERMINAL_PAGE_BUD_WDW_RECEIVER  14923
	#define IDC_TERMINAL_PAGE_BUD_WDW_HISTORY  14924
	#define IDC_TERMINAL_PAGE_BUD_WDW_HISTORYTYPE  14925
	
	#define IDC_TERMINAL_PAGE_BUD_PLANNING  1493
	
	#define IDC_TERMINAL_PAGE_TRANSFER  1500
	#define IDC_TERMINAL_PAGE_TFR_ABOUT  1501
	#define IDC_TERMINAL_PAGE_TFR_INPUT  1502
	#define IDC_TERMINAL_PAGE_TFR_RECEIVER  1503
	#define IDC_TERMINAL_PAGE_TFR_CONFIRM  1504
	
	#define IDC_TERMINAL_PAGE_ACCESS  1510
	#define IDC_TERMINAL_PAGE_ACS_LIST  1511
	#define IDC_TERMINAL_PAGE_ACS_CHECKUSER  1512
	#define IDC_TERMINAL_PAGE_ACS_CHECKGUEST  1513
	#define IDC_TERMINAL_PAGE_ACS_CONFIRM  1514
	
	
	
	/*DENIED DIALOG*/
	
	#define IDD_DENIED_DIALOG  1601
	#define IDC_DENIED_DIALOG_MESSAGE 1602
	
	/*SELECT FACTION DIALOG*/
	
	#define IDD_SELECTFACTION_DIALOG  1701
	#define IDC_SELECTFACTION_SCREEN  1702
	#define IDC_SELECTFACTION_1  1703
	#define IDC_SELECTFACTION_2  1704
	#define IDC_SELECTFACTION_3  1705
	#define IDC_SELECTFACTION_4  1706
	#define IDC_SELECTFACTION_5  1707
	
