class DefaultEventhandlers;
class CfgPatches
{
	class armst_Insections
	{
		units[]=
		{
			"armst_Insection",
			"armst_fireball",
			"armst_electraball"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR",
			"A3_Characters_F",
			"A3_Sounds_F",
			"A3_Data_F",
			"A3_Sounds_F",
			"A3_Anims_F"
		};
	};
};
class EventHandlers;
class CfgVehicles
{
	class B_Soldier_base_F;
	class Land;
	class Man: Land
	{
		class Eventhandlers;
	};
	class ARMST_MUTANT_HUM: B_Soldier_base_F
	{
		identityTypes[]=
		{
			"empty_Face"
		};
	};
	class armst_Insections_test: ARMST_MUTANT_HUM
	{
		uniformClass="armst_Insections_test";
		displayName="$STR_STST_insector_name";
		faceType="Default";
		model="\armst\armst_char\char_mut\Insections\Insections.p3d";
		armor=18;
		side=1;
		scope=1;
		faction="armst_mut_new";
		vehicleClass="armst_mutantss";
		canCarryBackPack=1;
		canDeactivateMines=1;
		engineer=1;
		attendant=1;
		weapons[]={};
		magazines[]={};
		respawnWeapons[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		class EventHandlers: EventHandlers
		{
			init="[_this select 0] spawn armst_fnc_insection;";
		};
		class Character
		{
			radius=200;
			detectionRadius=200;
			chaseDistance=201;
			coverRadius=100;
			escapeRadius=200;
			damage=0.18000001;
			damageHitPoints[]=
			{
				
				{
					"HitHead",
					0.5
				}
			};
			armor=90;
			attackDistances[]={4,6};
			allowWalk=0;
			aggressive=1;
			secrecy=0;
			curious=1;
			cowardice=0;
			societal=0;
			tactful=1;
			courage=100;
			friendly[]=
			{
				"armst_lepers_test"
			};
			class Sounds
			{
				idle[]=
				{
					"armst_Insection_sound",
					"armst_Insection_sound"
				};
				attack[]=
				{
					"armst_Insection_sound"
				};
				hit[]={};
				other[]={};
			};
			class Animations
			{
				attack_1[]=
				{
					"controler_attack1"
				};
				attack_2[]=
				{
					"controler_attack2",
					"controler_controll"
				};
				attack_3[]=
				{
					""
				};
				agry[]=
				{
					""
				};
				eat[]=
				{
					"controler_eat"
				};
			};
		};
		fsmFormation="armst_mutants\Logics\Formation.fsm";
		fsmDanger="armst_mutants\Logics\Danger.fsm";
		fsmInspect="armst_mutants\Logics\Inspect.fsm";
		fsmMove="armst_mutants\Logics\Move.fsm";
		fsmDead="armst_mutants\Logics\Dead.fsm";
		fsmAttack="armst\armst_char\char_mut\Insections\lepers.fsm";
	};
	class armst_Insection: armst_Insections_test
	{
		displayName="$STR_STST_insector_name";
		uniformClass="armst_Insection";
		model="\armst\armst_char\char_mut\Insections\Insections.p3d";
		uniformAccessories[]={};
		nakedUniform="armst_Insection";
		linkedItems[]={};
		nightVision=1;
		scope=2;
	};
	class armst_fireball_test: ARMST_MUTANT_HUM
	{
		uniformClass="armst_fireball_test";
		displayName="$STR_STST_anomaly_comet_name";
		faceType="Default";
		model="\armst\armst_char\char_mut\Insections\Insections.p3d";
		armor=20;
		side=1;
		scope=1;
		faction="armst_mut_new";
		vehicleClass="armst_mutantss";
		canCarryBackPack=1;
		canDeactivateMines=1;
		engineer=1;
		attendant=1;
		weapons[]={};
		magazines[]={};
		respawnWeapons[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		class EventHandlers: EventHandlers
		{
			init="[_this select 0] spawn armst_fnc_fireball;";
		};
		class Character
		{
			radius=200;
			detectionRadius=200;
			chaseDistance=201;
			coverRadius=100;
			escapeRadius=200;
			damage=0.69999999;
			damageHitPoints[]=
			{
				
				{
					"HitHead",
					1
				}
			};
			armor=90;
			attackDistances[]={4,6};
			allowWalk=0;
			aggressive=1;
			secrecy=0;
			curious=1;
			cowardice=0;
			societal=0;
			tactful=1;
			courage=100;
			friendly[]=
			{
				"armst_fireball_test"
			};
			class Sounds
			{
				idle[]=
				{
					"azSndAnomBurnIdle",
					"azSndAnomBurnIdle"
				};
				attack[]=
				{
					"azSndAnomBurnHit"
				};
				hit[]={};
				other[]={};
			};
			class Animations
			{
				attack_1[]=
				{
					"controler_attack1"
				};
				attack_2[]=
				{
					"controler_attack2",
					"controler_controll"
				};
				attack_3[]=
				{
					""
				};
				agry[]=
				{
					""
				};
				eat[]=
				{
					"controler_eat"
				};
			};
		};
		fsmFormation="armst_mutants\Logics\Formation.fsm";
		fsmDanger="armst_mutants\Logics\Danger.fsm";
		fsmInspect="armst_mutants\Logics\Inspect.fsm";
		fsmMove="armst_mutants\Logics\Move.fsm";
		fsmDead="armst_mutants\Logics\Dead.fsm";
		fsmAttack="armst\armst_char\char_mut\Insections\lepers.fsm";
	};
	class armst_fireball: armst_fireball_test
	{
		displayName="$STR_STST_anomaly_comet_name";
		uniformClass="armst_fireball";
		model="\armst\armst_char\char_mut\Insections\Insections.p3d";
		uniformAccessories[]={};
		nakedUniform="armst_fireball";
		linkedItems[]={};
		nightVision=1;
		scope=2;
	};
	class armst_electraball_test: ARMST_MUTANT_HUM
	{
		uniformClass="armst_electraball_test";
		displayName="$STR_STST_anomaly_tesla_name";
		faceType="Default";
		model="\armst\armst_char\char_mut\Insections\Insections.p3d";
		armor=20;
		side=1;
		scope=1;
		faction="armst_mut_new";
		vehicleClass="armst_mutantss";
		canCarryBackPack=1;
		canDeactivateMines=1;
		engineer=1;
		attendant=1;
		weapons[]={};
		magazines[]={};
		respawnWeapons[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		class EventHandlers: EventHandlers
		{
			init="[_this select 0] spawn armst_fnc_electraball;";
		};
		class Character
		{
			radius=200;
			detectionRadius=200;
			chaseDistance=201;
			coverRadius=100;
			escapeRadius=200;
			damage=0.60000002;
			damageHitPoints[]=
			{
				
				{
					"HitHead",
					1
				}
			};
			armor=90;
			attackDistances[]={4,6};
			allowWalk=0;
			aggressive=1;
			secrecy=0;
			curious=1;
			cowardice=0;
			societal=0;
			tactful=1;
			courage=100;
			friendly[]=
			{
				"armst_fireball_test"
			};
			class Sounds
			{
				idle[]=
				{
					"azSndAnomElectraIdle",
					"azSndAnomElectraIdle"
				};
				attack[]=
				{
					"anomaly_electra_blowout"
				};
				hit[]={};
				other[]={};
			};
			class Animations
			{
				attack_1[]=
				{
					"controler_attack1"
				};
				attack_2[]=
				{
					"controler_attack2",
					"controler_controll"
				};
				attack_3[]=
				{
					""
				};
				agry[]=
				{
					""
				};
				eat[]=
				{
					"controler_eat"
				};
			};
		};
		fsmFormation="armst_mutants\Logics\Formation.fsm";
		fsmDanger="armst_mutants\Logics\Danger.fsm";
		fsmInspect="armst_mutants\Logics\Inspect.fsm";
		fsmMove="armst_mutants\Logics\Move.fsm";
		fsmDead="armst_mutants\Logics\Dead.fsm";
		fsmAttack="armst\armst_char\char_mut\Insections\lepers.fsm";
	};
	class armst_electraball: armst_electraball_test
	{
		displayName="$STR_STST_anomaly_tesla_name";
		uniformClass="armst_electraball";
		model="\armst\armst_char\char_mut\Insections\Insections.p3d";
		uniformAccessories[]={};
		nakedUniform="armst_electraball";
		linkedItems[]={};
		nightVision=1;
		scope=2;
	};
};
class CfgSounds
{
	class armst_Insection_sound
	{
		name="armst_Insection_sound";
		sound[]=
		{
			"\armst\armst_char\char_mut\Insections\armst_Insection_sound.ogg",
			2,
			1
		};
		titles[]={};
	};
};
