class CfgPatches
{
	class SP_Goggles
	{
		units[]=
		{
			"armst_BFGasMask",
			"armst_BioGasMask",
			"armst_GP5",
			"armst_GP7",
			"armst_m50"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]={};
	};
};
class CfgGlasses
{
	class None
	{
		author="ArmSTALKER";
		ACE_Color[]={0,0,0};
		ACE_TintAmount=0;
		ACE_Overlay="";
		ACE_OverlayDirt="A3\Ui_f\data\igui\rsctitles\HealthTextures\dust_upper_ca.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\textures\HUD\Cracked.paa";
		ACE_Resistance=0;
		ACE_Protection=0;
		ACE_DustPath="\armst\armst_kom\GasMasks\textures\fx\dust\%4.paa";
	};
	class G_Combat: None
	{
		ACE_Overlay="\armst\armst_kom\GasMasks\textures\HUD\CombatGoggles.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\textures\HUD\CombatGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class Armst_balaclava_dolg: None
	{
		scope=1;
		displayname="Balaclava";
		model="\armst\armst_kom\gasmasks\band_balaclava.p3d";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
	};
	class Armst_balaclava_voen: None
	{
		scope=1;
		displayname="Balaclava";
		model="\armst\armst_kom\gasmasks\band_balaclava.p3d";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
	};
	class Armst_BalaclavaFreed: None
	{
		scope=1;
		displayname="Balaclava";
		model="\armst\armst_kom\gasmasks\band_balaclava.p3d";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
	};
	class G_Diving
	{
		author="ArmSTALKER";
		ACE_Overlay="\armst\armst_kom\GasMasks\textures\HUD\DivingGoggles.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\textures\HUD\DivingGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskM40: None
	{
		scope=2;
		displayname="$STR_gasmaskM40";
		model="\armst\armst_kom\gasmasks\gasmask1.p3d";
		picture="\armst\armst_kom\GasMasks\ui\GP7ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\m04_overlay_ca_5.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskM40_1: None
	{
		scope=2;
		displayname="$STR_gasmaskM40";
		model="\armst\armst_kom\gasmasks\gasmask1_1.p3d";
		picture="\armst\armst_kom\GasMasks\ui\GP7ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\m04_overlay_ca_5.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskM41: None
	{
		scope=2;
		displayname="$STR_gasmaskM40";
		model="\armst\armst_kom\gasmasks\gasmask1_1.p3d";
		picture="\armst\armst_kom\GasMasks\ui\GP7ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\m04_overlay_ca_5.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskm04: None
	{
		scope=2;
		displayname="$STR_gasmaskm04";
		model="\armst\armst_kom\gasmasks\armst_m04.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_m04.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\d1_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskm04_2: None
	{
		scope=2;
		displayname="$STR_gasmaskm04";
		model="\armst\armst_kom\gasmasks\armst_m04_2.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_m04.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\d1_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskm04_4: None
	{
		scope=2;
		displayname="$STR_gasmaskm04";
		model="\armst\armst_kom\gasmasks\armst_m04_4.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_m04.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\d1_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskm04_3: None
	{
		scope=2;
		displayname="$STR_gasmaskm04";
		model="\armst\armst_kom\gasmasks\armst_m04_3.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_m04.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\d1_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskm04s10: None
	{
		scope=2;
		displayname="$STR_gasmaskm04";
		model="\armst\armst_kom\gasmasks\armst_m04s10.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_m04.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\d1_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmasks10: None
	{
		scope=2;
		displayname="$STR_gasmasks10";
		model="\armst\armst_kom\gasmasks\armst_s10.p3d";
		picture="\armst\armst_kom\GasMasks\ui\s10.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\s10\s10_balaclava_dry_blue_co.paa"
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\s10_overlay_ca_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmasks10black: None
	{
		scope=2;
		displayname="$STR_gasmasks10";
		model="\armst\armst_kom\gasmasks\armst_s10.p3d";
		picture="\armst\armst_kom\GasMasks\ui\s10.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\s10\s10_balaclava_dry_black.paa"
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\s10_overlay_ca_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmasks10_orden: None
	{
		scope=2;
		displayname="$STR_gasmasks10";
		model="\armst\armst_kom\gasmasks\armst_s10.p3d";
		picture="\armst\armst_kom\GasMasks\ui\s10.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\s10\s10_balaclava_dry_black.paa"
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\s10_overlay_ca_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmasks10_flr: None
	{
		scope=2;
		displayname="$STR_gasmasks10";
		model="\armst\armst_kom\gasmasks\armst_s10.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_s10_gasmask_flr_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\textures\s10_gasmask_flr_validol.paa"
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\s10_overlay_ca_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmasks10_ppk: None
	{
		scope=2;
		displayname="$STR_gasmasks10";
		model="\armst\armst_kom\gasmasks\armst_s10.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_s10_gasmask_ppk_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\textures\s10_gasmask_ppk_validol.paa"
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\s10_overlay_ca_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmasks10_ttr: None
	{
		scope=2;
		displayname="$STR_gasmasks10";
		model="\armst\armst_kom\gasmasks\armst_s10.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_s10_gasmask_ttr_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\textures\s10_gasmask_ttr_validol.paa"
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\s10_overlay_ca_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmasks10_2: None
	{
		scope=2;
		displayname="$STR_gasmasks10";
		model="\armst\armst_kom\gasmasks\armst_s10.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_s10_gasmask_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\textures\s10_gasmask_validol.paa"
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\s10_overlay_ca_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskM50_2: None
	{
		scope=2;
		displayname="$STR_gasmaskM50_2";
		model="\armst\armst_kom\gasmasks\armst_m50_2.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_m50_2.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\M50_4.paa";
		hiddenSelections[]={};
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskM50_2_multicam: None
	{
		scope=2;
		displayname="$STR_gasmaskM50_2";
		model="\armst\armst_kom\gasmasks\armst_m50_2.p3d";
		picture="\armst\armst_kom\GasMasks\m50_2\icon_m50-2_multi_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\m50_2\m50_2_multi_validol.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\M50_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmask_albino: None
	{
		scope=2;
		displayname="Mask GsMs";
		model="\armst\armst_kom\gasmasks\armst_albedo_gas.p3d";
		picture="\armst\armst_kom\GasMasks\ui\gasmask_albino.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\M50_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmask_albino_2: None
	{
		scope=2;
		displayname="Mask GsMs";
		model="\armst\armst_kom\gasmasks\armst_albedo_gas.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_GsMs_black_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\M50_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\GsMs_black_validol.paa"
		};
	};
	class armst_gasmask_albino_3: None
	{
		scope=2;
		displayname="Mask GsMs";
		model="\armst\armst_kom\gasmasks\armst_albedo_gas.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_GsMs_grey_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\M50_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\GsMs_grey_validol.paa"
		};
	};
	class armst_cigar_face: None
	{
		scope=1;
		displayname="$STR_ciga";
		model="\armst\armst_kom\GasMasks\cigarette.p3d";
		picture="\armst\armst_item\img\siga.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava3_silent: None
	{
		scope=2;
		displayname="$STR_armst_balaclava3";
		model="\armst\armst_kom\gasmasks\armst_balaclava_2.p3d";
		picture="\armst\armst_kom\GasMasks\balaclava\silent.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balaclava\Balaclava_co_silent.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava3_smile: None
	{
		scope=2;
		displayname="$STR_armst_balaclava3";
		model="\armst\armst_kom\gasmasks\armst_balaclava_2.p3d";
		picture="\armst\armst_kom\GasMasks\balaclava\smile.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balaclava\Balaclava_co_smile.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava3_des: None
	{
		scope=2;
		displayname="$STR_armst_balaclava3";
		model="\armst\armst_kom\gasmasks\armst_balaclava_2.p3d";
		picture="\armst\armst_kom\GasMasks\balaclava\des.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balaclava\Balaclava_co_des.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava3_wcam: None
	{
		scope=2;
		displayname="$STR_armst_balaclava3";
		model="\armst\armst_kom\gasmasks\armst_balaclava_2.p3d";
		picture="\armst\armst_kom\GasMasks\balaclava\wcam.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balaclava\Balaclava_co_wcam.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava3_urbcam: None
	{
		scope=2;
		displayname="$STR_armst_balaclava3";
		model="\armst\armst_kom\gasmasks\armst_balaclava_2.p3d";
		picture="\armst\armst_kom\GasMasks\balaclava\urbcam.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balaclava\Balaclava_co_urbcam.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava3_multicam: None
	{
		scope=2;
		displayname="$STR_armst_balaclava3";
		model="\armst\armst_kom\gasmasks\armst_balaclava_2.p3d";
		picture="\armst\armst_kom\GasMasks\balaclava\multicam.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balaclava\Balaclava_co_multicam.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava3_green: None
	{
		scope=2;
		displayname="$STR_armst_balaclava3";
		model="\armst\armst_kom\gasmasks\armst_balaclava_2.p3d";
		picture="\armst\armst_kom\GasMasks\balaclava\green.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balaclava\Balaclava_co_grn.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava3_black: None
	{
		scope=2;
		displayname="$STR_armst_balaclava3";
		model="\armst\armst_kom\gasmasks\armst_balaclava_2.p3d";
		picture="\armst\armst_kom\GasMasks\balaclava\black.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balaclava\Balaclava_co_blk.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava3_skull: None
	{
		scope=2;
		displayname="$STR_armst_balaclava3";
		model="\armst\armst_kom\gasmasks\armst_balaclava_2.p3d";
		picture="\armst\armst_kom\GasMasks\balaclava\skull.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balaclava\Balaclava_co.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_podshlemnik_olive: None
	{
		scope=2;
		displayname="Balaclava (Olive)";
		model="\armst\armst_kom\GasMasks\podshlemnik.p3d";
		picture="\armst\armst_kom\GasMasks\ui\band_balaclava.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\podshlemnik\bl.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_podshlemnik_olive2: None
	{
		scope=2;
		displayname="Balaclava (Olive 2)";
		model="\armst\armst_kom\GasMasks\podshlemnik.p3d";
		picture="\armst\armst_kom\GasMasks\ui\band_balaclava.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\podshlemnik\bl2.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_podshlemnik_green: None
	{
		scope=2;
		displayname="Balaclava (Green)";
		model="\armst\armst_kom\GasMasks\podshlemnik.p3d";
		picture="\armst\armst_kom\GasMasks\ui\band_balaclava.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\podshlemnik\bl3.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_podshlemnik_blue: None
	{
		scope=2;
		displayname="Balaclava (Blue)";
		model="\armst\armst_kom\GasMasks\podshlemnik.p3d";
		picture="\armst\armst_kom\GasMasks\ui\band_balaclava.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\podshlemnik\bl4.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_podshlemnik_red: None
	{
		scope=2;
		displayname="Balaclava (Red)";
		model="\armst\armst_kom\GasMasks\podshlemnik.p3d";
		picture="\armst\armst_kom\GasMasks\ui\band_balaclava.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\podshlemnik\bl5.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_podshlemnik_white: None
	{
		scope=2;
		displayname="Balaclava (White)";
		model="\armst\armst_kom\GasMasks\podshlemnik.p3d";
		picture="\armst\armst_kom\GasMasks\ui\band_balaclava.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\podshlemnik\bl6.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_band_balaclava_3: None
	{
		scope=2;
		displayname="$STR_armst_band_balaclava";
		model="\armst\armst_kom\gasmasks\band_balaclava.p3d";
		picture="\armst\armst_kom\GasMasks\ui\band_balaclava.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_char\char_man\bandits\new_bandit\B_1\bandos_kap_co3.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_balaclava_1: None
	{
		author="ArmSTALKER";
		_generalMacro="G_Balaclava_blk";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_clean0";
		model="\armst\armst_kom\GasMasks\armst_balaklava.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_clean_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_balaklava.paa"
		};
		identityTypes[]={};
		mass=6;
	};
	class armst_balaclava_3: armst_balaclava_1
	{
		author="ArmSTALKER";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\armst\armst_kom\GasMasks\armst_balaklava.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_stalk1_balaklava_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\stalk1_balaklava_validol.paa"
		};
		identityTypes[]={};
	};
	class armst_balaclava_4: armst_balaclava_1
	{
		author="ArmSTALKER";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\armst\armst_kom\GasMasks\armst_balaklava.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_stalk2_balaklava_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\stalk2_balaklava_validol.paa"
		};
		identityTypes[]={};
	};
	class armst_balaclava_5: armst_balaclava_1
	{
		author="ArmSTALKER";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\armst\armst_kom\GasMasks\armst_balaklava.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_stalk3_balaklava_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\stalk3_balaklava_validol.paa"
		};
		identityTypes[]={};
	};
	class armst_balaclava_clearsky: armst_balaclava_1
	{
		author="ArmSTALKER";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\armst\armst_kom\GasMasks\armst_balaklava.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_CS_balaklava_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\CS_balaklava_validol.paa"
		};
		identityTypes[]={};
	};
	class armst_balaclava_freedom: armst_balaclava_1
	{
		author="ArmSTALKER";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\armst\armst_kom\GasMasks\armst_balaklava.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_freedom_balaklava_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\freedom_balaklava_validol.paa"
		};
		identityTypes[]={};
	};
	class armst_balaclava_merc: armst_balaclava_1
	{
		author="ArmSTALKER";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\armst\armst_kom\GasMasks\armst_balaklava.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_merc_balaklava_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\merc_balaklava_validol.paa"
		};
		identityTypes[]={};
	};
	class armst_balaclava_monolith: armst_balaclava_1
	{
		author="ArmSTALKER";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\armst\armst_kom\GasMasks\armst_balaklava.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_mono_balaklava_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\mono_balaklava_validol.paa"
		};
		identityTypes[]={};
	};
	class armst_balaclava_army: armst_balaclava_1
	{
		author="ArmSTALKER";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\armst\armst_kom\GasMasks\armst_balaklava.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_voen_balaklava_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\voen_balaklava_validol.paa"
		};
		identityTypes[]={};
	};
	class G_Balaclava_blk: None
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_blk";
		scope=1;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_clean0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_balaclava_clean.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_clean_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_bootcamp\guerrilla\data\headgear_balaclava_blk_co.paa"
		};
		identityTypes[]={};
		mass=6;
	};
	class G_Balaclava_oli: G_Balaclava_blk
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="G_Balaclava_oli";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_oli0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_balaclava_clean.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_olive_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\headgear_balaclava_grn_co.paa"
		};
		identityTypes[]={};
	};
	class armst_respirator: None
	{
		scope=2;
		displayname="$STR_respirator";
		model="\armst\armst_kom\gasmasks\respirator.p3d";
		picture="\armst\armst_kom\GasMasks\ui\RespiratoRico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=70;
	};
	class armst_one_eye: None
	{
		scope=2;
		displayname="$STR_one_eye";
		model="\armst\armst_kom\gasmasks\one_eye.p3d";
		picture="\armst\armst_kom\GasMasks\ui\one_eye.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\1.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_2: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\2.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_3: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\3.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_4: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\4.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_5: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\5.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_6: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\6.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_7: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\7.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_8: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\8.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_9: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\9.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_orden: None
	{
		scope=2;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask4_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\orden.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_mask_min: None
	{
		scope=1;
		armor=20;
		displayname="$STR_armst_mask";
		model="\armst\armst_kom\gasmasks\armst_mask_br.p3d";
		picture="\armst\armst_kom\GasMasks\mask\mask6_ru.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\mask\10.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard.p3d";
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head1.paa"
		};
		ACE_Protection=1;
	};
	class armst_beard_2: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard.p3d";
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head2.paa"
		};
		ACE_Protection=1;
	};
	class armst_beard_3: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard.p3d";
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head3.paa"
		};
		ACE_Protection=1;
	};
	class armst_beard2: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard2.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head1.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard2_2: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard2.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head2.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard2_3: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard2.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head3.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard3: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard3.p3d";
		picture="";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head1.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard3_2: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard3.p3d";
		picture="";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head2.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard3_3: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard3.p3d";
		picture="";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head3.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard4: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard4.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head1.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard4_2: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard4.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head2.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard4_3: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard4.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head3.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard5: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard5.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head1.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard5_2: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard5.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head2.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_beard5_3: None
	{
		scope=2;
		displayname="Beard";
		model="\armst\armst_kom\gasmasks\beard5.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\beard\head3.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskBastard: None
	{
		scope=2;
		displayname="$STR_armst_gasmaskBastard";
		model="\armst\armst_kom\gasmasks\gasmask2.p3d";
		picture="\armst\armst_kom\GasMasks\Data\ubl_boloto_UI.paa";
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\b1_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\t2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		armst_radiation=60;
	};
	class armst_G100: None
	{
		scope=2;
		displayname="$STR_gasmaskG100";
		model="\armst\armst_kom\gasmasks\BFGasMask.p3d";
		picture="\armst\armst_kom\GasMasks\ui\G100ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\Issledovatel_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\r2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=28;
	};
	class armst_G100_2: None
	{
		scope=2;
		displayname="$STR_gasmaskG100";
		model="\armst\armst_kom\gasmasks\BFGasMask.p3d";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\Issledovatel_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\r2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=28;
		picture="\armst\armst_kom\GasMasks\textures\icon_G100_bezh_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\textures\G100_bezh_validol.paa"
		};
	};
	class armst_G100_science: None
	{
		scope=2;
		displayname="$STR_gasmaskG100";
		model="\armst\armst_kom\gasmasks\BFGasMask.p3d";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\Issledovatel_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\r2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=28;
		picture="\armst\armst_kom\GasMasks\textures\icon_G100_ecolog_validol.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\textures\G100_ecolog_validol.paa"
		};
	};
	class armst_GasBal: None
	{
		scope=2;
		displayname="$STR_GasBal";
		model="\armst\armst_kom\gasmasks\GASBAL.p3d";
		picture="\armst\armst_kom\GasMasks\ui\gasbal_ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP7_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=30;
	};
	class armst_GasBal_orden: None
	{
		scope=2;
		displayname="Gasmask with balloon (Improved)";
		model="\armst\armst_kom\gasmasks\GASBAL.p3d";
		picture="\armst\armst_kom\GasMasks\ui\gasbal_ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP7_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=30;
	};
	class armst_BioGasMaskG25: None
	{
		scope=2;
		displayname="$STR_gasmaskG25";
		model="\armst\armst_kom\gasmasks\BioGasMask.p3d";
		picture="\armst\armst_kom\GasMasks\ui\g25ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP7_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=30;
	};
	class armst_GasP5: None
	{
		scope=2;
		displayname="$STR_gasmaskGP5";
		model="\armst\armst_kom\gasmasks\GP5.p3d";
		picture="\armst\armst_kom\GasMasks\ui\gp5ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP5_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\t2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=60;
	};
	class armst_GasP5_2: None
	{
		scope=2;
		displayname="$STR_gasmaskGP5";
		model="\armst\armst_kom\gasmasks\GP5.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_GP5_gasmask_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP5_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\t2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=60;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\GP5_gasmask_validol.paa"
		};
	};
	class armst_GasP7: None
	{
		scope=2;
		displayname="$STR_gasmaskGP7";
		model="\armst\armst_kom\gasmasks\GP7.p3d";
		picture="\armst\armst_kom\GasMasks\ui\GP7ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP7_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=60;
	};
	class armst_Gasslon: None
	{
		scope=2;
		displayname="$STR_Gasslon";
		model="\armst\armst_kom\gasmasks\slon.p3d";
		picture="\armst\armst_kom\GasMasks\ui\SLONG-gico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\SLONG-G_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=55;
	};
	class armst_Gasslon_2: None
	{
		scope=2;
		displayname="$STR_Gasslon";
		model="\armst\armst_kom\gasmasks\slon.p3d";
		picture="\armst\armst_kom\GasMasks\textures\icon_slonG_bezh_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\SLONG-G_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=55;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\textures\slonG_bezh_validol.paa"
		};
	};
	class armst_Gasscout: None
	{
		scope=2;
		displayname="$STR_gasmaskResearcher";
		model="\armst\armst_kom\gasmasks\scout.p3d";
		picture="\armst\armst_kom\GasMasks\ui\Issledovatelico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\Issledovatel_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=45;
	};
	class armst_gasm20: None
	{
		scope=2;
		displayname="$STR_gasmaskM2";
		model="\armst\armst_kom\gasmasks\m2.p3d";
		picture="\armst\armst_kom\GasMasks\ui\M2ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\M50_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=24;
	};
	class armst_M334: None
	{
		scope=2;
		displayname="GP-U";
		model="\armst\armst_kom\gasmasks\M334.p3d";
		picture="\armst\armst_kom\GasMasks\ui\GP_Uico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\Issledovatel_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=24;
	};
	class armst_M334_2: None
	{
		scope=2;
		displayname="GP-U";
		model="\armst\armst_kom\gasmasks\M334.p3d";
		picture="\armst\armst_kom\GasMasks\Data\ubl_boloto_UI.paa";
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\Issledovatel_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\Data\ubl_boloto.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		armst_radiation=60;
	};
	class armst_M334_duty: None
	{
		scope=2;
		displayname="GP-U";
		model="\armst\armst_kom\gasmasks\M334.p3d";
		picture="\armst\armst_kom\GasMasks\Data\ubl_duty_UI.paa";
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\Issledovatel_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\Data\ubl_duty.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		armst_radiation=60;
	};
	class armst_M334_freedom: None
	{
		scope=2;
		displayname="GP-U";
		model="\armst\armst_kom\gasmasks\M334.p3d";
		picture="\armst\armst_kom\GasMasks\Data\ubl_freedom_UI.paa";
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\Issledovatel_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"armst\armst_kom\GasMasks\Data\ubl_freedom.paa"
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		armst_radiation=60;
	};
	class armst_gasm50: None
	{
		scope=2;
		displayname="$STR_gasmaskM50";
		model="\armst\armst_kom\gasmasks\m50.p3d";
		picture="\armst\armst_kom\GasMasks\ui\M50ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\M50_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=25;
	};
	class armst_MESHOK: None
	{
		scope=2;
		displayname="$STR_MESHOK0";
		model="\armst\armst_kom\gasmasks\MESHOK.p3d";
		picture="\armst\armst_kom\GasMasks\ui\MESHOKico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\MESHOKui.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		armst_radiation=60;
	};
	class armst_bandana: None
	{
		scope=2;
		displayname="$STR_Bandana";
		model="\armst\armst_kom\gasmasks\bandana.p3d";
		picture="\armst\armst_kom\GasMasks\ui\bandanaico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_m33: None
	{
		scope=2;
		displayname="$STR_gasmaskM33";
		model="\armst\armst_kom\gasmasks\M33.p3d";
		picture="\armst\armst_kom\GasMasks\ui\M33.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP7_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=1;
		ACE_Protection=1;
		armst_radiation=45;
	};
	class armst_hiddengasmask: None
	{
		scope=1;
		displayname="$STR_gasmaskM33";
		model="\armst\armst_kom\gasmasks\FallGasMask.p3d";
		picture="\armst\armst_kom\GasMasks\ui\M33.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP7_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=1;
		ACE_Protection=1;
		armst_radiation=45;
	};
	class armst_bandanaGlass: None
	{
		scope=2;
		displayname="$STR_Bandana2";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\ui\bandanaGlassico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_bandanaGlass_2: None
	{
		scope=2;
		displayname="$STR_Bandana2";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\armst_bandanaGlass\icon_stalk1_bandana_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_bandanaGlass\stalk1_bandana_validol.paa"
		};
	};
	class armst_bandanaGlass_3: None
	{
		scope=2;
		displayname="$STR_Bandana2";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\armst_bandanaGlass\icon_stalk2_bandana_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_bandanaGlass\stalk2_bandana_validol.paa"
		};
	};
	class armst_bandanaGlass_4: None
	{
		scope=2;
		displayname="$STR_Bandana2";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\armst_bandanaGlass\icon_stalk3_bandana_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_bandanaGlass\stalk3_bandana_validol.paa"
		};
	};
	class armst_bandanaGlass_clearsky: None
	{
		scope=2;
		displayname="$STR_Bandana_cs";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\armst_bandanaGlass\icon_cs_bandana_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_bandanaGlass\cs_bandana_validol.paa"
		};
	};
	class armst_bandanaGlass_duty: None
	{
		scope=2;
		displayname="$STR_Bandana_duty";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\armst_bandanaGlass\icon_duty_bandana_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_bandanaGlass\duty_bandana_validol.paa"
		};
	};
	class armst_bandanaGlass_freedom: None
	{
		scope=2;
		displayname="$STR_Bandana_freedom";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\armst_bandanaGlass\icon_freedom_bandana_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_bandanaGlass\freedom_bandana_validol.paa"
		};
	};
	class armst_bandanaGlass_merc: None
	{
		scope=2;
		displayname="$STR_Bandana_merc";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\armst_bandanaGlass\icon_merc_bandana_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_bandanaGlass\merc_bandana_validol.paa"
		};
	};
	class armst_bandanaGlass_monolith: None
	{
		scope=2;
		displayname="$STR_Bandana_monolith";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\armst_bandanaGlass\icon_mono_bandana_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_bandanaGlass\mono_bandana_validol.paa"
		};
	};
	class armst_bandanaGlass_army: None
	{
		scope=2;
		displayname="$STR_Bandana_army";
		model="\armst\armst_kom\gasmasks\bandanaGlass.p3d";
		picture="\armst\armst_kom\GasMasks\armst_bandanaGlass\icon_voen_bandana_validol.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=2;
		ACE_Protection=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\armst_bandanaGlass\voen_bandana_validol.paa"
		};
	};
	class armst_seva_visor: None
	{
		scope=2;
		displayname="Visor (SEVA)";
		model="\armst\armst_kom\gasmasks\seva.p3d";
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\SLONG-G_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\GUI\SLONG-G_4.paa";
		picture="\armst\armst_kom\GasMasks\ui\bandanaGlassico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=0;
		ACE_Protection=0;
	};
	class armst_gluhar_visor: None
	{
		scope=2;
		displayname="Visor (Gluhar)";
		model="\armst\armst_kom\gasmasks\gluhar.p3d";
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\SLONG-G_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\GUI\SLONG-G_4.paa";
		picture="\armst\armst_kom\GasMasks\ui\bandanaGlassico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=0;
		ACE_Protection=0;
	};
	class armst_CN2f: None
	{
		scope=2;
		displayname="$STR_armst_CN2f";
		model="\armst\armst_kom\gasmasks\armst_CN2f.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_CN2f.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=0;
		ACE_Protection=0;
	};
	class armst_CN3p: None
	{
		scope=2;
		displayname="$STR_armst_CN3p";
		model="\armst\armst_kom\gasmasks\armst_CN3p.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_CN3p.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=0;
		ACE_Protection=0;
	};
	class armst_R5: None
	{
		scope=2;
		displayname="$STR_gasmaskR5";
		model="\armst\armst_kom\gasmasks\armst_R5.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=0;
		ACE_Protection=0;
	};
	class armst_R5_filter: None
	{
		scope=2;
		displayname="$STR_gasmaskR51";
		model="\armst\armst_kom\gasmasks\armst_R5_filter.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_filter.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=0;
		ACE_Protection=0;
		armst_radiation=55;
	};
	class armst_R5_P: None
	{
		scope=2;
		displayname="$STR_gasmaskR5Р";
		model="\armst\armst_kom\gasmasks\armst_R5_P.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_P.paa";
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\SLONG-G_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=1;
		ACE_Protection=1;
	};
	class armst_R5_P_black: None
	{
		scope=2;
		displayname="$STR_gasmaskR5Р";
		model="\armst\armst_kom\gasmasks\armst_R5_P_black.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_P.paa";
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\SLONG-G_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=1;
		ACE_Protection=1;
	};
	class armst_R5_P_filter: None
	{
		scope=2;
		displayname="$STR_gasmaskR5Р1";
		model="\armst\armst_kom\gasmasks\armst_R5_P_filter.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_P_filter.paa";
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\SLONG-G_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=1;
		ACE_Protection=1;
		armst_radiation=30;
	};
	class armst_R5_SH2: None
	{
		scope=2;
		displayname="$STR_gasmaskR5SH2";
		model="\armst\armst_kom\gasmasks\armst_R5_SH2.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_SH2.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP7_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=1;
		ACE_Protection=1;
	};
	class armst_R5_SH2_filter: None
	{
		scope=2;
		displayname="$STR_gasmaskR5SH21";
		model="\armst\armst_kom\gasmasks\armst_R5_SH2_filter.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_SH2_filter.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\GP7_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=1;
		ACE_Protection=1;
		armst_radiation=26;
	};
	class armst_gasmaskM40_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskM40";
		model="\armst\armst_kom\gasmasks\gasmask1.p3d";
		picture="\armst\armst_kom\GasMasks\ui\GP7ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="\armst\armst_kom\GasMasks\GUI\c1_4.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\c2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasmaskBastard_broken: None
	{
		scope=1;
		displayname="$STR_armst_gasmaskBastard";
		model="\armst\armst_kom\gasmasks\gasmask2.p3d";
		picture="\armst\armst_kom\GasMasks\ui\GP7ico.paa";
		ACE_Overlay="\armst\armst_kom\GasMasks\UIdata\t2.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\t2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
	};
	class armst_G100_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskG100";
		model="\armst\armst_kom\gasmasks\BFGasMask.p3d";
		picture="\armst\armst_kom\GasMasks\ui\G100ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\g100_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\r2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_BioGasMaskG25_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskG25";
		model="\armst\armst_kom\gasmasks\BioGasMask.p3d";
		picture="\armst\armst_kom\GasMasks\ui\g25ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\g25_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_GasP5_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskGP5";
		model="\armst\armst_kom\gasmasks\GP5.p3d";
		picture="\armst\armst_kom\GasMasks\ui\gp5ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\gp5_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\t2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_GasP7_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskGP7";
		model="\armst\armst_kom\gasmasks\GP7.p3d";
		picture="\armst\armst_kom\GasMasks\ui\GP7ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\gp7_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_Gasslon_broken: None
	{
		scope=1;
		displayname="$STR_Gasslon";
		model="\armst\armst_kom\gasmasks\slon.p3d";
		picture="\armst\armst_kom\GasMasks\ui\SLONG-gico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\SLONG-g_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_Gasscout_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskResearcher";
		model="\armst\armst_kom\gasmasks\scout.p3d";
		picture="\armst\armst_kom\GasMasks\ui\Issledovatelico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\Issledovatel_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasm20_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskM2";
		model="\armst\armst_kom\gasmasks\m2.p3d";
		picture="\armst\armst_kom\GasMasks\ui\M2ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\M50_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_gasm50_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskM50";
		model="\armst\armst_kom\gasmasks\m50.p3d";
		picture="\armst\armst_kom\GasMasks\ui\M50ico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\M50_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\d2.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class armst_seva_visor_broken: None
	{
		scope=1;
		displayname="$STR_GlassSEVA";
		model="\armst\armst_kom\gasmasks\seva.p3d";
		ACE_Overlay="armst\armst_kom\GasMasks\ui\SLONG-g_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		picture="\armst\armst_kom\GasMasks\ui\bandanaGlassico.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=0;
		ACE_Protection=0;
	};
	class armst_R5_P_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskR5Р";
		model="\armst\armst_kom\gasmasks\armst_R5_P.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_P.paa";
		ACE_Overlay="armst\armst_kom\GasMasks\ui\SLONG-g_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=1;
		ACE_Protection=1;
	};
	class armst_R5_P_filter_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskR5Р1";
		model="\armst\armst_kom\gasmasks\armst_R5_P_filter.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_P_filter.paa";
		ACE_Overlay="armst\armst_kom\GasMasks\ui\SLONG-g_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\e2.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Resistance=1;
		ACE_Protection=1;
	};
	class armst_R5_SH2_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskR5SH2";
		model="\armst\armst_kom\gasmasks\armst_R5_SH2.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_SH2.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\g25_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=1;
		ACE_Protection=1;
	};
	class armst_R5_SH2_filter_broken: None
	{
		scope=1;
		displayname="$STR_gasmaskR5SH21";
		model="\armst\armst_kom\gasmasks\armst_R5_SH2_filter.p3d";
		picture="\armst\armst_kom\GasMasks\ui\armst_R5_SH2_filter.paa";
		identityTypes[]=
		{
			"NoGlasses",
			1000
		};
		ACE_Overlay="armst\armst_kom\GasMasks\ui\g25_broken.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\UIdata\f2.paa";
		ACE_Resistance=1;
		ACE_Protection=1;
	};
	class G_Lowprofile: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class G_Shades_Black: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
	};
	class G_Shades_Blue: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Shades_Green: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Shades_Red: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Spectacles: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Spectacles_Tinted: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
	};
	class G_Sport_Blackred: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Sport_BlackWhite: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Sport_Blackyellow: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
	};
	class G_Sport_Checkered: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
	};
	class G_Sport_Greenblack: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
	};
	class G_Sport_Red: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Color[]={0,0,0};
		ACE_Resistance=1;
	};
	class G_Squares: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Squares_Tinted: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Tactical_Black: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Tactical_Clear: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Aviator: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Lady_Blue: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Lady_Red: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class G_Lady_Dark: None
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
	};
	class G_Lady_Mirror: None
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
	};
	class AV_ESS_blk: None
	{
		ACE_Overlay="\armst\armst_kom\GasMasks\textures\HUD\CombatGoggles.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\textures\HUD\CombatGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class G_Balaclava_combat: G_Balaclava_blk
	{
		ACE_Overlay="\armst\armst_kom\GasMasks\textures\HUD\CombatGoggles.paa";
		ACE_OverlayCracked="\armst\armst_kom\GasMasks\textures\HUD\CombatGogglesCracked.paa";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class G_Balaclava_lowprofile: G_Balaclava_blk
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=2;
		ACE_Protection=1;
	};
	class G_Bandanna_blk;
	class G_Bandanna_shades: G_Bandanna_blk
	{
		ACE_TintAmount="8.0*2";
		ACE_Resistance=1;
		ACE_Protection=1;
	};
	class G_Bandanna_sport: G_Bandanna_blk
	{
		ACE_TintAmount=8;
		ACE_Resistance=1;
		ACE_Protection=1;
	};
	class G_Bandanna_aviator_black: None
	{
		displayname="Bandana with aviators";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_bandana_aviator.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_aviator_ca.paa";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\armst\armst_kom\GasMasks\balacl\blk_co.paa"
		};
	};
};
class CfgVehicles
{
	class All
	{
	};
	class AllVehicles: All
	{
	};
	class Land: AllVehicles
	{
	};
	class Static: All
	{
	};
	class Building: Static
	{
	};
	class armst_BFGasMask: Building
	{
		scope=2;
		displayname="Mask BFGasMask";
		model="\armst\armst_kom\gasmasks\BFGasMask.p3d";
		destrType="DestructNo";
	};
	class armst_BioGasMask: Building
	{
		scope=2;
		displayname="Mask BioGasMask";
		model="\armst\armst_kom\gasmasks\BioGasMask.p3d";
		destrType="DestructNo";
	};
	class armst_GP5: Building
	{
		scope=2;
		displayname="Mask GP5";
		model="\armst\armst_kom\gasmasks\GP5.p3d";
		destrType="DestructNo";
	};
	class armst_GP7: Building
	{
		scope=2;
		displayname="Mask GP7";
		model="\armst\armst_kom\gasmasks\GP7.p3d";
		destrType="DestructNo";
	};
	class armst_m50: Building
	{
		scope=2;
		displayname="Mask m50";
		model="\armst\armst_kom\gasmasks\m50.p3d";
		destrType="DestructNo";
	};
};
