	
	#include "..\__application.sqf";
		
	#define MODULE_NAME Camp
	
	//GUI Definitions
	#include "\armst_client\GUI\Classes\definitions.hpp";
			
	#define IDC_RSCDISPLAYCAMPVIEWER					198700
	#define IDC_RSCDISPLAYCAMPVIEWER_MOUSEAREA          198701
	
	#define DIK_W               0x11
	#define DIK_S               0x1F
	#define DIK_A               0x1E
	#define DIK_D               0x20
	#define DIK_ESCAPE          0x01
	
	#define IDC_RSCCONTROL_MAINCONTROLSAREA				198802
	
	#define IDC_RSCCONTROL_RESOURCES_TREE				198803
	#define IDC_RSCCONTROL_RESOURCES_LISTBOX			198804	
	#define IDC_RSCCONTROL_RESOURCES_LISTBOX_TITLE		198805	
	#define IDC_RSCCONTROL_RESOURCES_LISTBOX_GRUUP		198806
	
	#define IDC_RSCCONTROL_STORAGE_LISTBOX_GROUP		198807
	#define IDC_RSCCONTROL_STORAGE_LISTBOX				198808
	#define IDC_RSCCONTROL_STORAGE_TRANSFER_BUTTON		198809
	#define IDC_RSCCONTROL_STORAGE_TRANSFER_EDIT		198810
		
	#define IDC_RSCCONTROL_OBJECTS_TREE 				198811
	
	#define IDC_RSCCONTROL_RESOURCES_DELETE 			198812
	#define IDC_RSCCONTROL_RESOURCES_CREATE 			198813
	#define IDC_RSCCONTROL_RESOURCES_UPDATE 			198814
	
	#define IDC_RSCCONTROL_PARTY_LISTBOX 				198815
	#define IDC_RSCCONTROL_PARTY_DELETE 				198816
	#define IDC_RSCCONTROL_PARTY_TOGGLE 				198817
	#define IDC_RSCCONTROL_PARTY_LISTBOX_GRUUP_ADD 		198818
	#define IDC_RSCCONTROL_PARTY_LISTBOX_ADD 			198819
	#define IDC_RSCCONTROL_PARTY_ADD	 				198820
	#define IDC_RSCCONTROL_PARTY_TOGGLELIST 			198821

	
	