class CfgPatches
{
	class armst_anomalies
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]={};
	};
	class armst_anom
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]={};
	};
	class arms_anomaly
	{
		units[]={};
		weapons[]={};
		requiredVersion=1;
		requiredAddons[]={};
	};
	class AZCUTTER
	{
		units[]={};
		weapons[]={};
		requiredVersion=1;
		requiredAddons[]={};
	};
};
class CfgSounds
{
	class anomal_activate_souls
	{
		name="SOULS";
		sound[]=
		{
			"armst_anomalies\sounds\SOULS.ogg",
			1,
			1,
			100
		};
		titles[]={};
	};
	class anomal_hit_souls
	{
		name="SOULS_HIT";
		sound[]=
		{
			"armst_anomalies\sounds\SOULS_HIT.ogg",
			1,
			1,
			100
		};
		titles[]={};
	};
	class gravi_idle2
	{
		name="gravi_idle";
		sound[]=
		{
			"armst_anomalies\sounds\gravi_idle.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class emi_idle
	{
		name="emi_idle";
		sound[]=
		{
			"armst_anomalies\sounds\emi_idle.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class dead_krik
	{
		name="dead_krik";
		sound[]=
		{
			"armst_anomalies\sounds\dead_krik.ogg",
			1,
			1,
			100
		};
		titles[]={};
	};
	class kostolom_idle
	{
		name="kostolom_idle";
		sound[]=
		{
			"armst_anomalies\sounds\kostolom_idle.ogg",
			1,
			1,
			100
		};
		titles[]={};
	};
	class kostolom_activated
	{
		name="kostolom_activated";
		sound[]=
		{
			"armst_anomalies\sounds\kostolom_activated.ogg",
			4,
			1,
			100
		};
		titles[]={};
	};
	class fireball_idle
	{
		name="fireball_idle";
		sound[]=
		{
			"armst_anomalies\sounds\fireball_idle.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class monolith_idle
	{
		name="monolith_idle";
		sound[]=
		{
			"armst_anomalies\sounds\monolith_idle.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class teleport_idle
	{
		name="teleport_idle";
		sound[]=
		{
			"armst_anomalies\sounds\teleport_idle.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class teleport_work_1
	{
		name="teleport_work_1";
		sound[]=
		{
			"armst_anomalies\sounds\teleport_work_1.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class MEAT_ACTIVATE
	{
		name="teleport_work_1";
		sound[]=
		{
			"armst_anomalies\sounds\MEAT_ACTIVATE.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class MEAT_HIT
	{
		name="MEAT_HIT";
		sound[]=
		{
			"armst_anomalies\sounds\MEAT_HIT.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class RJAVICNA_HIT
	{
		name="RJAVICNA_HIT";
		sound[]=
		{
			"armst_anomalies\sounds\RJAVICNA_HIT.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class anomaly_gravy_blowout
	{
		name="anomaly_gravy_blowout";
		sound[]=
		{
			"armst_anomalies\sounds\anomaly_gravy_blowout.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class anomaly_gravy_hit
	{
		name="anomaly_gravy_hit";
		sound[]=
		{
			"armst_anomalies\sounds\anomaly_gravy_hit.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class anomaly_electra_blowout
	{
		name="anomaly_electra_blowout";
		sound[]=
		{
			"armst_anomalies\sounds\anomaly_electra_blowout.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class anomaly_Burn_hit
	{
		name="anomaly_Burn_hit";
		sound[]=
		{
			"armst_anomalies\sounds\anomaly_Burn_hit.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class azSndAnomBurnHit
	{
		sound[]=
		{
			"\armst_anomalies\Sounds\Burn_Hit.ogg",
			1,
			1,
			100
		};
		name="azSndAnomBurnHit";
		titles[]={};
	};
	class azSndAnomBurnIdle
	{
		sound[]=
		{
			"\armst_anomalies\Sounds\Burn_Idle.ogg",
			2,
			1,
			100
		};
		name="azSndAnomBurnIdle";
		titles[]={};
	};
	class azSndAnomElectraIdle
	{
		sound[]=
		{
			"\armst_anomalies\Sounds\Electra_Idle.ogg",
			2,
			1,
			100
		};
		name="azSndAnomElectraIdle";
		titles[]={};
	};
	class azSndAnomElectraHit
	{
		sound[]=
		{
			"\armst_anomalies\Sounds\Electra_Hit.ogg",
			1,
			1,
			100
		};
		name="azSndAnomElectraHit";
		titles[]={};
	};
	class azSndAnomGraviIdle
	{
		sound[]=
		{
			"\armst_anomalies\Sounds\Gravi_Idle.ogg",
			2,
			1,
			100
		};
		name="azSndAnomGraviIdle";
		titles[]={};
	};
	class azSndAnomGraviHit
	{
		sound[]=
		{
			"\armst_anomalies\Sounds\Gravi_Hit2.ogg",
			1,
			1,
			100
		};
		name="azSndAnomGraviHit";
		titles[]={};
	};
	class azSndAnomGraviIdlePlus
	{
		sound[]=
		{
			"\armst_anomalies\Sounds\Gravi_Idle_plus.ogg",
			2,
			1,
			100
		};
		name="azSndAnomGraviIdlePlus";
		titles[]={};
	};
	class azSndAnomGraviHitPlus
	{
		sound[]=
		{
			"\armst_anomalies\Sounds\Gravi_Hit_Plus.ogg",
			1,
			1,
			100
		};
		name="azSndAnomGraviHitPlus";
		titles[]={};
	};
	class anomaly_buzz_hit
	{
		sound[]=
		{
			"\armst_anomalies\Sounds\anomaly_buzz_hit.ogg",
			1,
			1,
			100
		};
		name="anomaly_buzz_hit";
		titles[]={};
	};
	class studen
	{
		name="studen";
		sound[]=
		{
			"\armst\Armst_sound\anomaly\studen.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class gravi2
	{
		name="gravi2";
		sound[]=
		{
			"\armst\Armst_sound\anomaly\gravi2.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class gravi
	{
		name="gravi";
		sound[]=
		{
			"\armst\Armst_sound\anomaly\gravi.ogg",
			2,
			1,
			100
		};
		titles[]={};
	};
	class armst_talk_ghosts2
	{
		sound[]=
		{
			"\armst\armst_sound\objects\armst_talk_ghosts.ogg",
			1,
			1,
			50
		};
		titles[]={};
	};
	class armst_silovoepole2
	{
		sound[]=
		{
			"\armst\armst_sound\objects\armst_silovoepole.ogg",
			1,
			1,
			100
		};
		titles[]={};
	};
	class radio_bar_1
	{
		name="radio_bar_1";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\dolbitnarmaln.ogg",
			0.30000001,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_2
	{
		name="radio_bar_2";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\bandits.ogg",
			0.30000001,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_3
	{
		name="radio_bar_2";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\dolg.ogg",
			0.30000001,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_4
	{
		name="radio_bar_4";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\freedoms.ogg",
			0.30000001,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_5
	{
		name="radio_bar_5";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\bandit.ogg",
			10,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_6
	{
		name="radio_bar_6";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\bar.ogg",
			10,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_7
	{
		name="radio_bar_7";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\dolg.ogg",
			10,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_8
	{
		name="radio_bar_8";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\freedom.ogg",
			10,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_9
	{
		name="radio_bar_9";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\science.ogg",
			10,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_10
	{
		name="radio_bar_10";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\rp.ogg",
			10,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_11
	{
		name="radio_bar_11";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\bratva1.ogg",
			10,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_12
	{
		name="radio_bar_12";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\musick.ogg",
			10,
			1,
			20
		};
		titles[]={};
	};
	class radio_bar_13
	{
		name="radio_bar_13";
		sound[]=
		{
			"\armst\armst_sound\stalker_radio\bezlik.ogg",
			10,
			1,
			20
		};
		titles[]={};
	};
};
class CfgVehicles
{
	class house_f;
	class armst_radio: house_f
	{
	};
	class armst_radio_bar_1: armst_radio
	{
		scope=2;
		displayName="radio_bar_1";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_1";
	};
	class armst_radio_bar_2: armst_radio
	{
		scope=2;
		displayName="radio_bar_2";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_2";
	};
	class armst_radio_bar_3: armst_radio
	{
		scope=2;
		displayName="radio_bar_3";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_3";
	};
	class armst_radio_bar_4: armst_radio
	{
		scope=2;
		displayName="radio_bar_4";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_4";
	};
	class armst_radio_bar_5: armst_radio
	{
		scope=2;
		displayName="radio_bar_5";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_5";
	};
	class armst_radio_bar_6: armst_radio
	{
		scope=2;
		displayName="radio_bar_6";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_6";
	};
	class armst_radio_bar_7: armst_radio
	{
		scope=2;
		displayName="radio_bar_7";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_7";
	};
	class armst_radio_bar_8: armst_radio
	{
		scope=2;
		displayName="radio_bar_6";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_6";
	};
	class armst_radio_bar_9: armst_radio
	{
		scope=2;
		displayName="radio_bar_9";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_9";
	};
	class armst_radio_bar_10: armst_radio
	{
		scope=2;
		displayName="radio_bar_10";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_10";
	};
	class armst_radio_bar_11: armst_radio
	{
		scope=2;
		displayName="radio_bar_11";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_11";
	};
	class armst_radio_bar_12: armst_radio
	{
		scope=2;
		displayName="armst_radio_bar_12";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_12";
	};
	class armst_radio_bar_13: armst_radio
	{
		scope=2;
		displayName="armst_radio_bar_13";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="radio_bar_13";
	};
	class armst_silovoepole2: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="armst_silovoepole2";
	};
	class armst_idle_ghost_idle: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\armst_ghosts.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="armst_talk_ghosts2";
	};
	class armst_idle_teleport_idle: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="teleport_idle";
	};
	class armst_idle_GraviIdle: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="azSndAnomGraviIdle";
	};
	class armst_idle_emi_idle: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="emi_idle";
	};
	class armst_idle_monolith_idle: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="monolith_idle";
	};
	class armst_idle_BurnIdle: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="azSndAnomBurnIdle";
	};
	class armst_idle_studen: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="studen";
	};
	class armst_idle_gravi2: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="gravi2";
	};
	class armst_idle_gravi: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="gravi";
	};
	class armst_idle_ElectraIdle: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="azSndAnomElectraIdle";
	};
	class armst_idle_kostolom_idle: armst_radio
	{
		scope=1;
		displayName="sound_idle";
		model="\armst_anomalies\sounds\sound_idle.p3d";
		vehicleClass="armst_obj_sounds";
		simulation="fountain";
		sound="kostolom_idle";
	};
	class Sound;
	class azSndSrcAnomBurnIdle: Sound
	{
		scope=2;
		sound="azSFXAnomBurnIdle";
		displayName="azSndSrcAnomBurnIdle";
	};
	class azSndSrcAnomBurnHit: Sound
	{
		scope=2;
		sound="azSFXAnomBurnHit";
		displayName="azSndSrcAnomBurnHit";
	};
	class azSndSrcAnomElectraIdle: Sound
	{
		scope=2;
		sound="azSFXAnomElectraIdle";
		displayName="azSndSrcAnomElectraIdle";
	};
	class azSndSrcAnomElectraHit: Sound
	{
		scope=2;
		sound="azSFXAnomElectraHit";
		displayName="azSndSrcAnomElectraHit";
	};
	class azSndSrcAnomGraviIdle: Sound
	{
		scope=2;
		sound="azSFXAnomGraviIdle";
		displayName="azSndSrcAnomGraviIdle";
	};
	class azSndSrcAnomGraviHit: Sound
	{
		scope=2;
		sound="azSFXAnomGraviHit";
		displayName="azSndSrcAnomGraviHit";
	};
	class azSndSrcAnomGraviIdlePlus: Sound
	{
		scope=2;
		sound="azSFXAnomGraviIdlePlus";
		displayName="azSndSrcAnomGraviIdlePlus";
	};
	class azSndSrcAnomGraviHitPlus: Sound
	{
		scope=2;
		sound="azSFXAnomGraviHitPlus";
		displayName="azSndSrcAnomGraviHitPlus";
	};
	class Thing;
	class arms_cutter: Thing
	{
		model="\armst_anomalies\anomaly\burn_decal_3.p3d";
		displayName="$STR_ARMS_CUTTER";
		icon="\A3\data_f\Unknown_object.paa";
		scope=2;
		simulation="thing";
		nameSound="";
		vehicleClass="Misc";
		transportFuel=0;
		mapSize=1;
		accuracy=0.2;
		cost=0;
		armor=200000;
		destrType="DestructNo";
	};
	class burn_decal: Thing
	{
		model="\armst_anomalies\anomaly\burn_decal_1.p3d";
		displayName="$STR_ARMS_BURN_DECAL_1";
		icon="\A3\data_f\Unknown_object.paa";
		scope=2;
		simulation="thing";
		nameSound="";
		vehicleClass="Misc";
		transportFuel=0;
		mapSize=1;
		accuracy=0.2;
		cost=0;
		armor=200000;
		destrType="DestructNo";
	};
	class burn_decal_2: burn_decal
	{
		model="\armst_anomalies\anomaly\burn_decal_2.p3d";
		displayName="$STR_ARMS_BURN_DECAL_2";
	};
	class AZ_CUTTER_BIG: Thing
	{
		model="\armst_anomalies\anomaly\cutter\Model\Big_Cutter.p3d";
		displayName="$STR_AZ_CUTTER_BIG";
		icon="\ca\data\data\Unknown_object.paa";
		scope=2;
		simulation="thing";
		nameSound="";
		vehicleClass="Misc";
		transportFuel=0;
		mapSize=0.69999999;
		accuracy=0.2;
		cost=0;
		armor=200000;
		destrType="DestructNo";
	};
	class AZ_CUTTER_MEDIUM: AZ_CUTTER_BIG
	{
		model="\armst_anomalies\anomaly\cutter\Model\Medium_Cutter.p3d";
		displayName="$STR_AZ_CUTTER_MEDIUM";
	};
	class AZ_CUTTER_SMALL: AZ_CUTTER_BIG
	{
		model="\armst_anomalies\anomaly\cutter\Model\Small_Cutter.p3d";
		displayName="$STR_AZ_CUTTER_SMALL";
	};
};
class CfgSFX
{
	class azSFXAnomBurnIdle
	{
		sounds[]=
		{
			"Burn_Idle"
		};
		name="Burn_Idle";
		Burn_Idle[]=
		{
			"armst_anomalies\sounds\Burn_Idle",
			"db+10",
			1,
			30,
			1,
			0,
			0,
			0
		};
		Empty[]=
		{
			"",
			0,
			0,
			0,
			0,
			0,
			0,
			0
		};
	};
	class azSFXAnomBurnHit
	{
		sounds[]=
		{
			"Burn_Hit"
		};
		name="Burn_Hit";
		Burn_Hit[]=
		{
			"armst_anomalies\sounds\Burn_Hit",
			"db+50",
			1,
			300,
			1,
			0,
			0,
			0
		};
		Empty[]=
		{
			"",
			0,
			0,
			0,
			0,
			0,
			0,
			0
		};
	};
	class azSFXAnomElectraIdle
	{
		sounds[]=
		{
			"Electra_Idle"
		};
		name="Electra_Idle";
		Electra_Idle[]=
		{
			"armst_anomalies\sounds\Electra_Idle",
			"db+20",
			1,
			60,
			1,
			0,
			0,
			0
		};
		Empty[]=
		{
			"",
			0,
			0,
			0,
			0,
			0,
			0,
			0
		};
	};
	class azSFXAnomElectraHit
	{
		sounds[]=
		{
			"Electra_Hit"
		};
		name="Electra_Hit";
		Electra_Hit[]=
		{
			"armst_anomalies\sounds\Electra_Hit",
			"db+50",
			1,
			300,
			1,
			0,
			0,
			0
		};
		Empty[]=
		{
			"",
			0,
			0,
			0,
			0,
			0,
			0,
			0
		};
	};
	class azSFXAnomGraviIdle
	{
		sounds[]=
		{
			"Gravi_Idle"
		};
		name="Gravi_Idle";
		Gravi_Idle[]=
		{
			"armst_anomalies\sounds\gravi_idle",
			"db+20",
			1,
			60,
			1,
			0,
			0,
			0
		};
		Empty[]=
		{
			"",
			0,
			0,
			0,
			0,
			0,
			0,
			0
		};
	};
	class azSFXAnomGraviHit
	{
		sounds[]=
		{
			"Gravi_Hit"
		};
		name="Gravi_Hit";
		Gravi_Hit[]=
		{
			"armst_anomalies\sounds\Gravi_Hit2",
			"db+50",
			1,
			300,
			1,
			0,
			0,
			0
		};
		Empty[]=
		{
			"",
			0,
			0,
			0,
			0,
			0,
			0,
			0
		};
	};
	class azSFXAnomGraviIdlePlus
	{
		sounds[]=
		{
			"Gravi_Idle_Plus"
		};
		name="Gravi_Idle_Plus";
		Gravi_Idle_Plus[]=
		{
			"armst_anomalies\sounds\gravi_idle_plus",
			"db+20",
			1,
			60,
			1,
			0,
			0,
			0
		};
		Empty[]=
		{
			"",
			0,
			0,
			0,
			0,
			0,
			0,
			0
		};
	};
	class azSFXAnomGraviHitPlus
	{
		sounds[]=
		{
			"Gravi_Hit_Plus"
		};
		name="Gravi_Hit_Plus";
		Gravi_Hit_Plus[]=
		{
			"armst_anomalies\sounds\Gravi_Hit_Plus",
			"db+50",
			1,
			300,
			1,
			0,
			0,
			0
		};
		Empty[]=
		{
			"",
			0,
			0,
			0,
			0,
			0,
			0,
			0
		};
	};
};
